# x86_64 boot stub - generated by Sage
# Multiboot2 compliant, transitions 32-bit -> 64-bit long mode

.section .multiboot, "a"
.align 8
multiboot_header:
	.long 3900595414
	.long 0
	.long 72
	.long 394371810
	.long 5
	.long 20
	.long 1024
	.long 768
	.long 32
	.long 0
	.long 1
	.long 20
	.long 6
	.long 8
	.long 14
	.long 0
	.long 0
	.long 8
multiboot_header_end:

.section .rodata
.align 16
gdt64:
	.quad 0
gdt64_code:
	.quad 0x00209A0000000000
gdt64_data:
	.quad 0x0000920000000000
gdt64_end:

gdt64_pointer:
	.short gdt64_end - gdt64 - 1
	.long gdt64

.section .text
.code32
.global _start
_start:
	# Save multiboot info pointer
	movl %ebx, %edi

	# Set up initial stack
	movl $stack_top, %esp

	# Clear BSS
	movl $__bss_start, %edi
	movl $__bss_end, %ecx
	subl %edi, %ecx
	shrl $2, %ecx
	xorl %eax, %eax
	rep stosl

	movl %ebx, %edi

	# Enable A20 line via port 0x92 (fast A20)
	inb $0x92, %al
	orb $0x02, %al
	andb $0xFE, %al
	outb %al, $0x92

.section .bss
.align 4096
pml4_table:
	.skip 4096
pdp_table:
	.skip 4096

	# Clear page tables
	movl $pml4_table, %edi
	xorl %eax, %eax
	movl $2048, %ecx
	rep stosl

	# PML4[0] -> PDP table
	movl $pdp_table, %eax
	orl $0x03, %eax
	movl %eax, (pml4_table)

	# PDP entries: 4 x 1GB pages (identity map 0-4GB)
	movl $0x00000083, (pdp_table)
	movl $0x40000083, (pdp_table + 8)
	movl $0x80000083, (pdp_table + 16)
	movl $0xC0000083, (pdp_table + 24)

	# Set CR4.PAE (Physical Address Extension)
	movl %cr4, %eax
	orl $0x20, %eax
	movl %eax, %cr4

	# Load PML4 into CR3
	movl $pml4_table, %eax
	movl %eax, %cr3

	# Set EFER.LME (Long Mode Enable)
	movl $0xC0000080, %ecx
	rdmsr
	orl $0x100, %eax
	wrmsr

	# Enable paging (CR0.PG) and protected mode (CR0.PE)
	movl %cr0, %eax
	orl $0x80000001, %eax
	movl %eax, %cr0

	# Load 64-bit GDT
	lgdt (gdt64_pointer)

	# Far jump to 64-bit code segment
	ljmp $0x08, $long_mode_start

.code64
long_mode_start:
	# Reload data segment registers
	movw $0x10, %ax
	movw %ax, %ds
	movw %ax, %es
	movw %ax, %fs
	movw %ax, %gs
	movw %ax, %ss

	# Set up 64-bit stack
	movq $stack_top, %rsp

	# Pass multiboot info pointer as first argument
	movl %edi, %edi

	# Call kernel main
	call kmain

	# Halt if kmain returns
halt:
	cli
	hlt
	jmp halt

.section .bss
.align 16
stack_bottom:
	.skip 16384
stack_top:

.section .bss
.global __bss_start
__bss_start:
.global __bss_end
__bss_end:
