@file:Suppress("UNUSED_PARAMETER", "UNUSED_VARIABLE", "NAME_SHADOWING")
package com.sage.test

// Generated by Sage Kotlin Backend
// https://github.com/sageLang/sage

import sage.runtime.*
import sage.runtime.SageRuntime as S
import kotlinx.coroutines.*

typealias SageVal = S.Value

fun format_feature(index: SageVal = S.nil, feature: SageVal = S.nil): SageVal {
    return S.add(S.add(S.str(S.add(index, S.num(1.0))), S.str(". ")), feature)
    return S.nil
}

fun get_greeting(): SageVal {
    return S.add(S.add(S.add(S.str("Welcome to "), app_name), S.str(" v")), version)
    return S.nil
}

var grade: S.Value = S.nil
var score: S.Value = S.nil
var name: S.Value = S.nil
var scores: S.Value = S.nil
var i: S.Value = S.nil
var features: S.Value = S.nil
var version: S.Value = S.nil
var app_name: S.Value = S.nil

fun main() {
    S.init()
    
    app_name = S.str("Hello Sage")
    version = S.str("3")
    features = S.array(S.str("Write Android apps in Sage"), S.str("Transpile to Kotlin automatically"), S.str("Full Gradle project generation"), S.str("Material 3 theming built-in"), S.str("No XML layout files needed"))
    S.printLn(get_greeting())
    S.printLn(S.str(""))
    S.printLn(S.str("Features:"))
    run {
        val _iter_1 = S.toIterable(S.range(S.len(features)))
        for (i in _iter_1) {
            S.printLn(format_feature(i, S.index(features, i)))
        }
    }
    S.printLn(S.str(""))
    S.printLn(S.add(S.str("Total features: "), S.str(S.len(features))))
    scores = S.dict("Alice" to S.num(95.0), "Bob" to S.num(87.0), "Charlie" to S.num(92.0))
    S.printLn(S.str(""))
    S.printLn(S.str("Scores:"))
    run {
        val _iter_2 = S.toIterable(S.dictKeys(scores))
        for (name in _iter_2) {
            score = S.index(scores, name)
            grade = S.str("C")
            if (S.truthy(S.gte(score, S.num(90.0)))) {
                grade = S.str("A")
            }
            if (S.truthy(S.gte(score, S.num(80.0)))) {
                if (S.truthy(S.lt(score, S.num(90.0)))) {
                    grade = S.str("B")
                }
            }
            S.printLn(S.add(S.add(S.add(S.add(S.add(S.add(S.str("  "), name), S.str(": ")), S.str(score)), S.str(" (")), grade), S.str(")")))
        }
    }
    
}
