# SageLang assembly output for x86_64
# Profile: hosted
# Generated by sage compiler

.text
.globl main

main:
  pushq %rbp
  movq %rsp, %rbp
  subq $256, %rsp
  jmp .L0
fib:
  # v0 = load global 'n'
  leaq sage_globals(%rip), %rdi
  leaq .LC0(%rip), %rsi
  call sage_rt_get_global
  movq %rax, -16(%rbp)
  movq %rdx, -8(%rbp)
  # v1 = number 1.000000
  movsd .LN0(%rip), %xmm0
  call sage_rt_number
  movq %rax, -32(%rbp)
  movq %rdx, -24(%rbp)
  # v2 = v0 cmp v1
  movq -16(%rbp), %rdi
  movq -8(%rbp), %rsi
  movq -32(%rbp), %rdx
  movq -24(%rbp), %rcx
  call sage_rt_lte
  movq %rax, -48(%rbp)
  movq %rdx, -40(%rbp)
  # branch v2 ? .L1 : .L3
  movl -48(%rbp), %eax
  movq -48(%rbp), %rdi
  movq -40(%rbp), %rsi
  call sage_rt_get_bool
  testl %eax, %eax
  jne .L1
  jmp .L3
.L1:
  # v3 = load global 'n'
  leaq sage_globals(%rip), %rdi
  leaq .LC0(%rip), %rsi
  call sage_rt_get_global
  movq %rax, -64(%rbp)
  movq %rdx, -56(%rbp)
  movq -64(%rbp), %rax
  movq -56(%rbp), %rdx
  leave
  ret
  jmp .L3
.L3:
  # v4 = load global 'n'
  leaq sage_globals(%rip), %rdi
  leaq .LC0(%rip), %rsi
  call sage_rt_get_global
  movq %rax, -80(%rbp)
  movq %rdx, -72(%rbp)
  # v5 = number 1.000000
  movsd .LN0(%rip), %xmm0
  call sage_rt_number
  movq %rax, -96(%rbp)
  movq %rdx, -88(%rbp)
  # v6 = v4 op v5
  movq -80(%rbp), %rdi
  movq -72(%rbp), %rsi
  movq -96(%rbp), %rdx
  movq -88(%rbp), %rcx
  call sage_rt_sub
  movq %rax, -112(%rbp)
  movq %rdx, -104(%rbp)
  # call fib
  call fib
  movq %rax, -128(%rbp)
  movq %rdx, -120(%rbp)
  # v8 = load global 'n'
  leaq sage_globals(%rip), %rdi
  leaq .LC0(%rip), %rsi
  call sage_rt_get_global
  movq %rax, -144(%rbp)
  movq %rdx, -136(%rbp)
  # v9 = number 2.000000
  movsd .LN1(%rip), %xmm0
  call sage_rt_number
  movq %rax, -160(%rbp)
  movq %rdx, -152(%rbp)
  # v10 = v8 op v9
  movq -144(%rbp), %rdi
  movq -136(%rbp), %rsi
  movq -160(%rbp), %rdx
  movq -152(%rbp), %rcx
  call sage_rt_sub
  movq %rax, -176(%rbp)
  movq %rdx, -168(%rbp)
  # call fib
  call fib
  movq %rax, -192(%rbp)
  movq %rdx, -184(%rbp)
  # v12 = v7 op v11
  movq -128(%rbp), %rdi
  movq -120(%rbp), %rsi
  movq -192(%rbp), %rdx
  movq -184(%rbp), %rcx
  call sage_rt_add
  movq %rax, -208(%rbp)
  movq %rdx, -200(%rbp)
  movq -208(%rbp), %rax
  movq -200(%rbp), %rdx
  leave
  ret
  movq -16(%rbp), %rax
  movq -8(%rbp), %rdx
  leave
  ret
.L0:
  jmp .L4
accumulate:
  # v13 = number 0.000000
  movsd .LN2(%rip), %xmm0
  call sage_rt_number
  movq %rax, -224(%rbp)
  movq %rdx, -216(%rbp)
  # store global 'total' = v13
  leaq sage_globals(%rip), %rdi
  leaq .LC1(%rip), %rsi
  movq -224(%rbp), %rdx
  movq -216(%rbp), %rcx
  call sage_rt_set_global
  # v14 = number 1.000000
  movsd .LN0(%rip), %xmm0
  call sage_rt_number
  movq %rax, -240(%rbp)
  movq %rdx, -232(%rbp)
  # store global 'current' = v14
  leaq sage_globals(%rip), %rdi
  leaq .LC2(%rip), %rsi
  movq -240(%rbp), %rdx
  movq -232(%rbp), %rcx
  call sage_rt_set_global
  jmp .L5
.L5:
  # v15 = load global 'current'
  leaq sage_globals(%rip), %rdi
  leaq .LC2(%rip), %rsi
  call sage_rt_get_global
  movq %rax, -256(%rbp)
  movq %rdx, -248(%rbp)
  # v16 = load global 'limit'
  leaq sage_globals(%rip), %rdi
  leaq .LC3(%rip), %rsi
  call sage_rt_get_global
  movq %rax, -272(%rbp)
  movq %rdx, -264(%rbp)
  # v17 = v15 cmp v16
  movq -256(%rbp), %rdi
  movq -248(%rbp), %rsi
  movq -272(%rbp), %rdx
  movq -264(%rbp), %rcx
  call sage_rt_lte
  movq %rax, -288(%rbp)
  movq %rdx, -280(%rbp)
  # branch v17 ? .L6 : .L7
  movl -288(%rbp), %eax
  movq -288(%rbp), %rdi
  movq -280(%rbp), %rsi
  call sage_rt_get_bool
  testl %eax, %eax
  jne .L6
  jmp .L7
.L6:
  # v18 = nil
  call sage_rt_nil
  movq %rax, -304(%rbp)
  movq %rdx, -296(%rbp)
  # v19 = load global 'total'
  leaq sage_globals(%rip), %rdi
  leaq .LC1(%rip), %rsi
  call sage_rt_get_global
  movq %rax, -320(%rbp)
  movq %rdx, -312(%rbp)
  # v20 = load global 'current'
  leaq sage_globals(%rip), %rdi
  leaq .LC2(%rip), %rsi
  call sage_rt_get_global
  movq %rax, -336(%rbp)
  movq %rdx, -328(%rbp)
  # v21 = v19 op v20
  movq -320(%rbp), %rdi
  movq -312(%rbp), %rsi
  movq -336(%rbp), %rdx
  movq -328(%rbp), %rcx
  call sage_rt_add
  movq %rax, -352(%rbp)
  movq %rdx, -344(%rbp)
  # v22 = string
  leaq .LC-1(%rip), %rdi
  call sage_rt_string
  movq %rax, -368(%rbp)
  movq %rdx, -360(%rbp)
  # call builtin dict_set
  movq -304(%rbp), %rdi
  movq -296(%rbp), %rsi
  call dict_set
  movq %rax, -384(%rbp)
  movq %rdx, -376(%rbp)
  # v24 = nil
  call sage_rt_nil
  movq %rax, -400(%rbp)
  movq %rdx, -392(%rbp)
  # v25 = load global 'current'
  leaq sage_globals(%rip), %rdi
  leaq .LC2(%rip), %rsi
  call sage_rt_get_global
  movq %rax, -416(%rbp)
  movq %rdx, -408(%rbp)
  # v26 = number 1.000000
  movsd .LN0(%rip), %xmm0
  call sage_rt_number
  movq %rax, -432(%rbp)
  movq %rdx, -424(%rbp)
  # v27 = v25 op v26
  movq -416(%rbp), %rdi
  movq -408(%rbp), %rsi
  movq -432(%rbp), %rdx
  movq -424(%rbp), %rcx
  call sage_rt_add
  movq %rax, -448(%rbp)
  movq %rdx, -440(%rbp)
  # v28 = string
  leaq .LC-1(%rip), %rdi
  call sage_rt_string
  movq %rax, -464(%rbp)
  movq %rdx, -456(%rbp)
  # call builtin dict_set
  movq -400(%rbp), %rdi
  movq -392(%rbp), %rsi
  call dict_set
  movq %rax, -480(%rbp)
  movq %rdx, -472(%rbp)
  jmp .L5
.L7:
  # v30 = load global 'total'
  leaq sage_globals(%rip), %rdi
  leaq .LC1(%rip), %rsi
  call sage_rt_get_global
  movq %rax, -496(%rbp)
  movq %rdx, -488(%rbp)
  movq -496(%rbp), %rax
  movq -488(%rbp), %rdx
  leave
  ret
  movq -16(%rbp), %rax
  movq -8(%rbp), %rdx
  leave
  ret
.L4:
  # v31 = number 0.000000
  movsd .LN2(%rip), %xmm0
  call sage_rt_number
  movq %rax, -512(%rbp)
  movq %rdx, -504(%rbp)
  # store global 'counter' = v31
  leaq sage_globals(%rip), %rdi
  leaq .LC4(%rip), %rsi
  movq -512(%rbp), %rdx
  movq -504(%rbp), %rcx
  call sage_rt_set_global
  jmp .L8
.L8:
  # v32 = load global 'counter'
  leaq sage_globals(%rip), %rdi
  leaq .LC4(%rip), %rsi
  call sage_rt_get_global
  movq %rax, -528(%rbp)
  movq %rdx, -520(%rbp)
  # v33 = number 3.000000
  movsd .LN3(%rip), %xmm0
  call sage_rt_number
  movq %rax, -544(%rbp)
  movq %rdx, -536(%rbp)
  # v34 = v32 cmp v33
  movq -528(%rbp), %rdi
  movq -520(%rbp), %rsi
  movq -544(%rbp), %rdx
  movq -536(%rbp), %rcx
  call sage_rt_lt
  movq %rax, -560(%rbp)
  movq %rdx, -552(%rbp)
  # branch v34 ? .L9 : .L10
  movl -560(%rbp), %eax
  movq -560(%rbp), %rdi
  movq -552(%rbp), %rsi
  call sage_rt_get_bool
  testl %eax, %eax
  jne .L9
  jmp .L10
.L9:
  # v35 = nil
  call sage_rt_nil
  movq %rax, -576(%rbp)
  movq %rdx, -568(%rbp)
  # v36 = load global 'counter'
  leaq sage_globals(%rip), %rdi
  leaq .LC4(%rip), %rsi
  call sage_rt_get_global
  movq %rax, -592(%rbp)
  movq %rdx, -584(%rbp)
  # v37 = number 1.000000
  movsd .LN0(%rip), %xmm0
  call sage_rt_number
  movq %rax, -608(%rbp)
  movq %rdx, -600(%rbp)
  # v38 = v36 op v37
  movq -592(%rbp), %rdi
  movq -584(%rbp), %rsi
  movq -608(%rbp), %rdx
  movq -600(%rbp), %rcx
  call sage_rt_add
  movq %rax, -624(%rbp)
  movq %rdx, -616(%rbp)
  # v39 = string
  leaq .LC-1(%rip), %rdi
  call sage_rt_string
  movq %rax, -640(%rbp)
  movq %rdx, -632(%rbp)
  # call builtin dict_set
  movq -576(%rbp), %rdi
  movq -568(%rbp), %rsi
  call dict_set
  movq %rax, -656(%rbp)
  movq %rdx, -648(%rbp)
  jmp .L8
.L10:
  # v41 = load global 'counter'
  leaq sage_globals(%rip), %rdi
  leaq .LC4(%rip), %rsi
  call sage_rt_get_global
  movq %rax, -672(%rbp)
  movq %rdx, -664(%rbp)
  # print v41
  movq -672(%rbp), %rdi
  movq -664(%rbp), %rsi
  call sage_rt_print
  # v42 = number 6.000000
  movsd .LN4(%rip), %xmm0
  call sage_rt_number
  movq %rax, -688(%rbp)
  movq %rdx, -680(%rbp)
  # call fib
  call fib
  movq %rax, -704(%rbp)
  movq %rdx, -696(%rbp)
  # store global 'answer' = v43
  leaq sage_globals(%rip), %rdi
  leaq .LC5(%rip), %rsi
  movq -704(%rbp), %rdx
  movq -696(%rbp), %rcx
  call sage_rt_set_global
  # v44 = load global 'answer'
  leaq sage_globals(%rip), %rdi
  leaq .LC5(%rip), %rsi
  call sage_rt_get_global
  movq %rax, -720(%rbp)
  movq %rdx, -712(%rbp)
  # print v44
  movq -720(%rbp), %rdi
  movq -712(%rbp), %rsi
  call sage_rt_print
  # v45 = number 5.000000
  movsd .LN5(%rip), %xmm0
  call sage_rt_number
  movq %rax, -736(%rbp)
  movq %rdx, -728(%rbp)
  # call accumulate
  call accumulate
  movq %rax, -752(%rbp)
  movq %rdx, -744(%rbp)
  # print v46
  movq -752(%rbp), %rdi
  movq -744(%rbp), %rsi
  call sage_rt_print
  # v47 = string
  leaq .LC6(%rip), %rdi
  call sage_rt_string
  movq %rax, -768(%rbp)
  movq %rdx, -760(%rbp)
  # v48 = number 5.000000
  movsd .LN5(%rip), %xmm0
  call sage_rt_number
  movq %rax, -784(%rbp)
  movq %rdx, -776(%rbp)
  # call fib
  call fib
  movq %rax, -800(%rbp)
  movq %rdx, -792(%rbp)
  # call builtin str
  movq -800(%rbp), %rdi
  movq -792(%rbp), %rsi
  call str
  movq %rax, -816(%rbp)
  movq %rdx, -808(%rbp)
  # v51 = v47 op v50
  movq -768(%rbp), %rdi
  movq -760(%rbp), %rsi
  movq -816(%rbp), %rdx
  movq -808(%rbp), %rcx
  call sage_rt_add
  movq %rax, -832(%rbp)
  movq %rdx, -824(%rbp)
  # print v51
  movq -832(%rbp), %rdi
  movq -824(%rbp), %rsi
  call sage_rt_print
  # v52 = load global 'answer'
  leaq sage_globals(%rip), %rdi
  leaq .LC5(%rip), %rsi
  call sage_rt_get_global
  movq %rax, -848(%rbp)
  movq %rdx, -840(%rbp)
  # v53 = number 8.000000
  movsd .LN6(%rip), %xmm0
  call sage_rt_number
  movq %rax, -864(%rbp)
  movq %rdx, -856(%rbp)
  # v54 = v52 cmp v53
  movq -848(%rbp), %rdi
  movq -840(%rbp), %rsi
  movq -864(%rbp), %rdx
  movq -856(%rbp), %rcx
  call sage_rt_eq
  movq %rax, -880(%rbp)
  movq %rdx, -872(%rbp)
  # branch v54 ? .L11 : .L12
  movl -880(%rbp), %eax
  movq -880(%rbp), %rdi
  movq -872(%rbp), %rsi
  call sage_rt_get_bool
  testl %eax, %eax
  jne .L11
  jmp .L12
.L11:
  # v55 = string
  leaq .LC7(%rip), %rdi
  call sage_rt_string
  movq %rax, -896(%rbp)
  movq %rdx, -888(%rbp)
  # print v55
  movq -896(%rbp), %rdi
  movq -888(%rbp), %rsi
  call sage_rt_print
  jmp .L13
.L12:
  # v56 = string
  leaq .LC8(%rip), %rdi
  call sage_rt_string
  movq %rax, -912(%rbp)
  movq %rdx, -904(%rbp)
  # print v56
  movq -912(%rbp), %rdi
  movq -904(%rbp), %rsi
  call sage_rt_print
  jmp .L13
.L13:
  xorl %eax, %eax
  leave
  ret

.section .rodata
.LC0:
  .asciz "n"
.LC1:
  .asciz "total"
.LC2:
  .asciz "current"
.LC3:
  .asciz "limit"
.LC4:
  .asciz "counter"
.LC5:
  .asciz "answer"
.LC6:
  .asciz "fib="
.LC7:
  .asciz "phase10-ok"
.LC8:
  .asciz "phase10-bad"
.LN0:
  .double 1.000000
.LN1:
  .double 2.000000
.LN2:
  .double 0.000000
.LN3:
  .double 3.000000
.LN4:
  .double 6.000000
.LN5:
  .double 5.000000
.LN6:
  .double 8.000000
