// Generated by Sage Kotlin Backend
// https://github.com/sageLang/sage
@file:Suppress("UNUSED_PARAMETER", "UNUSED_VARIABLE", "NAME_SHADOWING")

import sage.runtime.*
import sage.runtime.SageRuntime as S
import kotlinx.coroutines.*

typealias SageVal = S.Value

open class HttpClient : SageObject("HttpClient") {
    override val props = mutableMapOf<String, SageVal>()
    
    open fun `init`(): SageVal {
        S.setProperty(S.Value.Obj(this), "base_url", S.str(""))
        S.setProperty(S.Value.Obj(this), "headers", S.dict())
        return S.nil
    }
    
    open fun base(url: SageVal = S.nil): SageVal {
        S.setProperty(S.Value.Obj(this), "base_url", url)
        return S.Value.Obj(this)
        return S.nil
    }
    
    open fun header(key: SageVal = S.nil, value: SageVal = S.nil): SageVal {
        S.indexSet(S.getProperty(S.Value.Obj(this), "headers"), key, value)
        return S.Value.Obj(this)
        return S.nil
    }
    
    open fun `get`(path: SageVal = S.nil): SageVal {
        S.printLn(S.add(S.add(S.str("[HTTP] GET "), S.getProperty(S.Value.Obj(this), "base_url")), path))
        return S.dict("status" to S.num(200.0), "body" to S.str(""))
        return S.nil
    }
    
    open fun post(path: SageVal = S.nil, body: SageVal = S.nil): SageVal {
        S.printLn(S.add(S.add(S.str("[HTTP] POST "), S.getProperty(S.Value.Obj(this), "base_url")), path))
        return S.dict("status" to S.num(200.0), "body" to S.str(""))
        return S.nil
    }
    
}

open class Storage : SageObject("Storage") {
    override val props = mutableMapOf<String, SageVal>()
    
    open fun `init`(name: SageVal = S.nil): SageVal {
        S.setProperty(S.Value.Obj(this), "name", name)
        S.setProperty(S.Value.Obj(this), "data", S.dict())
        return S.nil
    }
    
    open fun `get`(key: SageVal = S.nil, default_val: SageVal = S.nil): SageVal {
        if (S.truthy(S.dictHas(S.getProperty(S.Value.Obj(this), "data"), key))) {
            return S.index(S.getProperty(S.Value.Obj(this), "data"), key)
        }
        return default_val
        return S.nil
    }
    
    open fun `set`(key: SageVal = S.nil, value: SageVal = S.nil): SageVal {
        S.indexSet(S.getProperty(S.Value.Obj(this), "data"), key, value)
        return S.Value.Obj(this)
        return S.nil
    }
    
    open fun remove(key: SageVal = S.nil): SageVal {
        S.dictDelete(S.getProperty(S.Value.Obj(this), "data"), key)
        return S.Value.Obj(this)
        return S.nil
    }
    
    open fun clear(): SageVal {
        S.setProperty(S.Value.Obj(this), "data", S.dict())
        return S.Value.Obj(this)
        return S.nil
    }
    
}

open class Intent : SageObject("Intent") {
    override val props = mutableMapOf<String, SageVal>()
    
    open fun `init`(action: SageVal = S.nil): SageVal {
        S.setProperty(S.Value.Obj(this), "action", action)
        S.setProperty(S.Value.Obj(this), "extras", S.dict())
        S.setProperty(S.Value.Obj(this), "target", S.nil)
        return S.nil
    }
    
    open fun to(target: SageVal = S.nil): SageVal {
        S.setProperty(S.Value.Obj(this), "target", target)
        return S.Value.Obj(this)
        return S.nil
    }
    
    open fun extra(key: SageVal = S.nil, value: SageVal = S.nil): SageVal {
        S.indexSet(S.getProperty(S.Value.Obj(this), "extras"), key, value)
        return S.Value.Obj(this)
        return S.nil
    }
    
    open fun send(): SageVal {
        S.printLn(S.add(S.add(S.add(S.str("[Intent] "), S.getProperty(S.Value.Obj(this), "action")), S.str(" -> ")), S.str(S.getProperty(S.Value.Obj(this), "target"))))
        return S.Value.Obj(this)
        return S.nil
    }
    
}

open class UIContext : SageObject("UIContext") {
    override val props = mutableMapOf<String, SageVal>()
    
    open fun `init`(screen_name: SageVal = S.nil): SageVal {
        S.setProperty(S.Value.Obj(this), "screen_name", screen_name)
        S.setProperty(S.Value.Obj(this), "elements", S.array())
        S.setProperty(S.Value.Obj(this), "indent_level", S.num(0.0))
        return S.nil
    }
    
    open fun column(): SageVal {
        S.push(S.getProperty(S.Value.Obj(this), "elements"), S.dict("type" to S.str("column"), "indent" to S.getProperty(S.Value.Obj(this), "indent_level")))
        S.setProperty(S.Value.Obj(this), "indent_level", S.add(S.getProperty(S.Value.Obj(this), "indent_level"), S.num(1.0)))
        return S.Value.Obj(this)
        return S.nil
    }
    
    open fun row(): SageVal {
        S.push(S.getProperty(S.Value.Obj(this), "elements"), S.dict("type" to S.str("row"), "indent" to S.getProperty(S.Value.Obj(this), "indent_level")))
        S.setProperty(S.Value.Obj(this), "indent_level", S.add(S.getProperty(S.Value.Obj(this), "indent_level"), S.num(1.0)))
        return S.Value.Obj(this)
        return S.nil
    }
    
    open fun end_block(): SageVal {
        if (S.truthy(S.gt(S.getProperty(S.Value.Obj(this), "indent_level"), S.num(0.0)))) {
            S.setProperty(S.Value.Obj(this), "indent_level", S.sub(S.getProperty(S.Value.Obj(this), "indent_level"), S.num(1.0)))
        }
        return S.Value.Obj(this)
        return S.nil
    }
    
    open fun text(content: SageVal = S.nil): SageVal {
        S.push(S.getProperty(S.Value.Obj(this), "elements"), S.dict("type" to S.str("text"), "content" to S.str(content)))
        return S.Value.Obj(this)
        return S.nil
    }
    
    open fun button(label: SageVal = S.nil, on_click: SageVal = S.nil): SageVal {
        S.push(S.getProperty(S.Value.Obj(this), "elements"), S.dict("type" to S.str("button"), "label" to label, "on_click" to on_click))
        return S.Value.Obj(this)
        return S.nil
    }
    
    open fun image(src: SageVal = S.nil): SageVal {
        S.push(S.getProperty(S.Value.Obj(this), "elements"), S.dict("type" to S.str("image"), "src" to src))
        return S.Value.Obj(this)
        return S.nil
    }
    
    open fun input_field(hint: SageVal = S.nil, on_change: SageVal = S.nil): SageVal {
        S.push(S.getProperty(S.Value.Obj(this), "elements"), S.dict("type" to S.str("input"), "hint" to hint, "on_change" to on_change))
        return S.Value.Obj(this)
        return S.nil
    }
    
    open fun spacer(height: SageVal = S.nil): SageVal {
        S.push(S.getProperty(S.Value.Obj(this), "elements"), S.dict("type" to S.str("spacer"), "height" to height))
        return S.Value.Obj(this)
        return S.nil
    }
    
    open fun divider(): SageVal {
        S.push(S.getProperty(S.Value.Obj(this), "elements"), S.dict("type" to S.str("divider")))
        return S.Value.Obj(this)
        return S.nil
    }
    
    open fun list_view(items: SageVal = S.nil, on_item: SageVal = S.nil): SageVal {
        S.push(S.getProperty(S.Value.Obj(this), "elements"), S.dict("type" to S.str("list"), "items" to items, "on_item" to on_item))
        return S.Value.Obj(this)
        return S.nil
    }
    
    open fun card(): SageVal {
        S.push(S.getProperty(S.Value.Obj(this), "elements"), S.dict("type" to S.str("card"), "indent" to S.getProperty(S.Value.Obj(this), "indent_level")))
        S.setProperty(S.Value.Obj(this), "indent_level", S.add(S.getProperty(S.Value.Obj(this), "indent_level"), S.num(1.0)))
        return S.Value.Obj(this)
        return S.nil
    }
    
    open fun switch_toggle(label: SageVal = S.nil, value: SageVal = S.nil, on_toggle: SageVal = S.nil): SageVal {
        S.push(S.getProperty(S.Value.Obj(this), "elements"), S.dict("type" to S.str("switch"), "label" to label, "value" to value, "on_toggle" to on_toggle))
        return S.Value.Obj(this)
        return S.nil
    }
    
    open fun slider(min_val: SageVal = S.nil, max_val: SageVal = S.nil, value: SageVal = S.nil, on_change: SageVal = S.nil): SageVal {
        S.push(S.getProperty(S.Value.Obj(this), "elements"), S.dict("type" to S.str("slider"), "min" to min_val, "max" to max_val, "value" to value, "on_change" to on_change))
        return S.Value.Obj(this)
        return S.nil
    }
    
    open fun navigate(screen_name: SageVal = S.nil): SageVal {
        S.printLn(S.add(S.str("[Nav] -> "), screen_name))
        return S.Value.Obj(this)
        return S.nil
    }
    
    open fun go_back(): SageVal {
        S.printLn(S.str("[Nav] <- back"))
        return S.Value.Obj(this)
        return S.nil
    }
    
    open fun toast(message: SageVal = S.nil): SageVal {
        S.printLn(S.add(S.str("[Toast] "), message))
        return S.Value.Obj(this)
        return S.nil
    }
    
    open fun snackbar(message: SageVal = S.nil): SageVal {
        S.printLn(S.add(S.str("[Snackbar] "), message))
        return S.Value.Obj(this)
        return S.nil
    }
    
    open fun dialog(title: SageVal = S.nil, message: SageVal = S.nil, on_ok: SageVal = S.nil): SageVal {
        S.printLn(S.add(S.add(S.add(S.str("[Dialog] "), title), S.str(": ")), message))
        return S.Value.Obj(this)
        return S.nil
    }
    
}

open class App : SageObject("App") {
    override val props = mutableMapOf<String, SageVal>()
    
    open fun `init`(name: SageVal = S.nil): SageVal {
        S.setProperty(S.Value.Obj(this), "name", name)
        S.setProperty(S.Value.Obj(this), "package_name", S.str("com.sage.app"))
        S.setProperty(S.Value.Obj(this), "min_sdk", S.num(24.0))
        S.setProperty(S.Value.Obj(this), "target_sdk", S.num(34.0))
        S.setProperty(S.Value.Obj(this), "theme_name", S.str("Material3"))
        S.setProperty(S.Value.Obj(this), "screens", S.dict())
        S.setProperty(S.Value.Obj(this), "start_screen", S.str("main"))
        S.setProperty(S.Value.Obj(this), "permissions", S.array())
        S.setProperty(S.Value.Obj(this), "orientation", S.str("unspecified"))
        return S.nil
    }
    
    open fun `package`(pkg: SageVal = S.nil): SageVal {
        S.setProperty(S.Value.Obj(this), "package_name", pkg)
        return S.Value.Obj(this)
        return S.nil
    }
    
    open fun theme(name: SageVal = S.nil): SageVal {
        S.setProperty(S.Value.Obj(this), "theme_name", name)
        return S.Value.Obj(this)
        return S.nil
    }
    
    open fun min_api(level: SageVal = S.nil): SageVal {
        S.setProperty(S.Value.Obj(this), "min_sdk", level)
        return S.Value.Obj(this)
        return S.nil
    }
    
    open fun permission(perm: SageVal = S.nil): SageVal {
        S.push(S.getProperty(S.Value.Obj(this), "permissions"), perm)
        return S.Value.Obj(this)
        return S.nil
    }
    
    open fun screen(name: SageVal = S.nil, builder: SageVal = S.nil): SageVal {
        S.indexSet(S.getProperty(S.Value.Obj(this), "screens"), name, builder)
        if (S.truthy(S.eq(S.len(S.dictKeys(S.getProperty(S.Value.Obj(this), "screens"))), S.num(1.0)))) {
            S.setProperty(S.Value.Obj(this), "start_screen", name)
        }
        return S.Value.Obj(this)
        return S.nil
    }
    
    open fun compose_screen(name: SageVal = S.nil, root_component: SageVal = S.nil): SageVal {
        S.indexSet(S.getProperty(S.Value.Obj(this), "screens"), name, root_component)
        if (S.truthy(S.eq(S.len(S.dictKeys(S.getProperty(S.Value.Obj(this), "screens"))), S.num(1.0)))) {
            S.setProperty(S.Value.Obj(this), "start_screen", name)
        }
        return S.Value.Obj(this)
        return S.nil
    }
    
    open fun start(screen_name: SageVal = S.nil): SageVal {
        S.setProperty(S.Value.Obj(this), "start_screen", screen_name)
        return S.Value.Obj(this)
        return S.nil
    }
    
    open fun launch(): SageVal {
        S.printLn(S.add(S.add(S.str("[App] "), S.getProperty(S.Value.Obj(this), "name")), S.str(" ready")))
        S.printLn(S.add(S.str("[App] Package: "), S.getProperty(S.Value.Obj(this), "package_name")))
        S.printLn(S.add(S.str("[App] Start screen: "), S.getProperty(S.Value.Obj(this), "start_screen")))
        S.printLn(S.add(S.str("[App] Screens: "), S.str(S.len(S.dictKeys(S.getProperty(S.Value.Obj(this), "screens"))))))
        return S.Value.Obj(this)
        return S.nil
    }
    
}

fun share_text(text: SageVal = S.nil): SageVal {
    var intent = S.newInstance("Intent", S.str("android.intent.action.SEND"))
    S.callMethod(intent, "extra", S.str("text"), text)
    return intent
    return S.nil
}

fun open_url(url: SageVal = S.nil): SageVal {
    var intent = S.newInstance("Intent", S.str("android.intent.action.VIEW"))
    S.callMethod(intent, "extra", S.str("url"), url)
    return intent
    return S.nil
}

var my_app: S.Value = S.nil

fun main() {
    S.init()
    
    S.registerClass("HttpClient") { args -> S.Value.Obj(HttpClient().also { it.sageInit(*args) }) }
    S.registerClass("Storage") { args -> S.Value.Obj(Storage().also { it.sageInit(*args) }) }
    S.registerClass("Intent") { args -> S.Value.Obj(Intent().also { it.sageInit(*args) }) }
    S.registerClass("UIContext") { args -> S.Value.Obj(UIContext().also { it.sageInit(*args) }) }
    S.registerClass("App") { args -> S.Value.Obj(App().also { it.sageInit(*args) }) }
    
    my_app = S.newInstance("App", S.str("Test"))
    S.callMethod(my_app, "launch")
    
}
