; SageLang LLVM IR - generated by sage compiler
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-pc-linux-gnu"

%SageValue = type { i32, i64 }

; Runtime function declarations
declare %SageValue @sage_rt_number(double)
declare %SageValue @sage_rt_bool(i32)
declare %SageValue @sage_rt_string(i8*)
declare %SageValue @sage_rt_nil()
declare %SageValue @sage_rt_add(%SageValue, %SageValue)
declare %SageValue @sage_rt_sub(%SageValue, %SageValue)
declare %SageValue @sage_rt_mul(%SageValue, %SageValue)
declare %SageValue @sage_rt_div(%SageValue, %SageValue)
declare %SageValue @sage_rt_mod(%SageValue, %SageValue)
declare %SageValue @sage_rt_eq(%SageValue, %SageValue)
declare %SageValue @sage_rt_neq(%SageValue, %SageValue)
declare %SageValue @sage_rt_lt(%SageValue, %SageValue)
declare %SageValue @sage_rt_gt(%SageValue, %SageValue)
declare %SageValue @sage_rt_lte(%SageValue, %SageValue)
declare %SageValue @sage_rt_gte(%SageValue, %SageValue)
declare %SageValue @sage_rt_and(%SageValue, %SageValue)
declare %SageValue @sage_rt_or(%SageValue, %SageValue)
declare %SageValue @sage_rt_not(%SageValue)
declare %SageValue @sage_rt_neg(%SageValue)
declare void @sage_rt_print(%SageValue)
declare %SageValue @sage_rt_str(%SageValue)
declare %SageValue @sage_rt_len(%SageValue)
declare %SageValue @sage_rt_tonumber(%SageValue)
declare %SageValue @sage_rt_array_new(i32)
declare void @sage_rt_array_set(%SageValue, i32, %SageValue)
declare %SageValue @sage_rt_array_push(%SageValue, %SageValue)
declare %SageValue @sage_rt_array_pop(%SageValue)
declare %SageValue @sage_rt_array_extend(%SageValue, %SageValue)
declare %SageValue @sage_rt_array_reverse(%SageValue)
declare %SageValue @sage_rt_array_contains(%SageValue, %SageValue)
declare %SageValue @sage_rt_array_index_of(%SageValue, %SageValue)
declare %SageValue @sage_rt_index(%SageValue, %SageValue)
declare %SageValue @sage_rt_is_truthy(%SageValue)
declare i32 @sage_rt_get_bool(%SageValue)
declare %SageValue @sage_rt_dict_new()
declare void @sage_rt_dict_set(%SageValue, i8*, %SageValue)
declare %SageValue @sage_rt_dict_get(%SageValue, i8*)
declare %SageValue @sage_rt_tuple_new(i32)
declare void @sage_rt_tuple_set(%SageValue, i32, %SageValue)
declare %SageValue @sage_rt_slice(%SageValue, %SageValue, %SageValue)
declare %SageValue @sage_rt_get_attr(%SageValue, i8*)
declare void @sage_rt_set_attr(%SageValue, i8*, %SageValue)
declare i32 @sage_rt_array_len(%SageValue)
declare %SageValue @sage_rt_range(%SageValue)
declare i32 @sage_rt_get_updated_idx(%SageValue, i32)
declare void @sage_rt_index_set(%SageValue, %SageValue, %SageValue)
declare %SageValue @sage_rt_dict_keys(%SageValue)
declare %SageValue @sage_rt_dict_values(%SageValue)
declare %SageValue @sage_rt_dict_has(%SageValue, %SageValue)
declare %SageValue @sage_rt_type(%SageValue)
declare %SageValue @sage_rt_chr(%SageValue)
declare %SageValue @sage_rt_ord(%SageValue)
declare %SageValue @sage_rt_input(%SageValue)
declare %SageValue @sage_rt_readfile(%SageValue)
declare %SageValue @sage_rt_writefile(%SageValue, %SageValue)
declare %SageValue @sage_rt_readbytes(%SageValue)
declare %SageValue @sage_rt_writebytes(%SageValue, %SageValue)
declare %SageValue @sage_rt_appendbytes(%SageValue, %SageValue)
declare %SageValue @sage_rt_exists(%SageValue)
declare %SageValue @sage_rt_load_weights(%SageValue)
declare %SageValue @sage_rt_forward_pass(%SageValue, %SageValue, %SageValue, %SageValue, %SageValue, %SageValue, %SageValue, %SageValue, %SageValue, %SageValue, %SageValue, %SageValue, %SageValue, %SageValue, %SageValue, %SageValue, %SageValue)
declare %SageValue @sage_rt_matmul(%SageValue, %SageValue, %SageValue, %SageValue, %SageValue)
declare %SageValue @sage_rt_rms_norm(%SageValue, %SageValue, %SageValue, %SageValue, %SageValue)
declare %SageValue @sage_rt_silu(%SageValue)
declare %SageValue @sage_rt_scale(%SageValue, %SageValue)
declare %SageValue @sage_rt_cross_entropy(%SageValue, %SageValue, %SageValue, %SageValue)
declare %SageValue @sage_rt_make_function(i8*)
declare %SageValue @sage_rt_call_dynamic(%SageValue, %SageValue*, i32)
declare void @abort() noreturn
declare %SageValue @sage_rt_bit_and(%SageValue, %SageValue)
declare %SageValue @sage_rt_bit_or(%SageValue, %SageValue)
declare %SageValue @sage_rt_bit_xor(%SageValue, %SageValue)
declare %SageValue @sage_rt_bit_not(%SageValue)
declare %SageValue @sage_rt_shl(%SageValue, %SageValue)
declare %SageValue @sage_rt_shr(%SageValue, %SageValue)

; GPU runtime declarations
declare %SageValue @sage_rt_gpu_has_vulkan()
declare %SageValue @sage_rt_gpu_has_opengl()
declare %SageValue @sage_rt_gpu_init(%SageValue, %SageValue)
declare %SageValue @sage_rt_gpu_init_opengl(%SageValue, %SageValue, %SageValue)
declare %SageValue @sage_rt_gpu_shutdown()
declare %SageValue @sage_rt_gpu_device_name()
declare %SageValue @sage_rt_gpu_device_limits()
declare %SageValue @sage_rt_gpu_last_error()
declare %SageValue @sage_rt_gpu_create_buffer(%SageValue, %SageValue, %SageValue)
declare %SageValue @sage_rt_gpu_destroy_buffer(%SageValue)
declare %SageValue @sage_rt_gpu_buffer_upload(%SageValue, %SageValue)
declare %SageValue @sage_rt_gpu_buffer_download(%SageValue)
declare %SageValue @sage_rt_gpu_buffer_size(%SageValue)
declare %SageValue @sage_rt_gpu_create_image(%SageValue, %SageValue, %SageValue, %SageValue, %SageValue)
declare %SageValue @sage_rt_gpu_create_image_3d(%SageValue, %SageValue, %SageValue, %SageValue, %SageValue)
declare %SageValue @sage_rt_gpu_destroy_image(%SageValue)
declare %SageValue @sage_rt_gpu_image_dims(%SageValue)
declare %SageValue @sage_rt_gpu_create_sampler(%SageValue, %SageValue, %SageValue)
declare %SageValue @sage_rt_gpu_create_sampler_advanced(%SageValue, %SageValue, %SageValue, %SageValue, %SageValue, %SageValue)
declare %SageValue @sage_rt_gpu_destroy_sampler(%SageValue)
declare %SageValue @sage_rt_gpu_load_shader(%SageValue, %SageValue)
declare %SageValue @sage_rt_gpu_load_shader_glsl(%SageValue, %SageValue)
declare %SageValue @sage_rt_gpu_reload_shader(%SageValue, %SageValue)
declare %SageValue @sage_rt_gpu_destroy_shader(%SageValue)
declare %SageValue @sage_rt_gpu_create_descriptor_layout(%SageValue)
declare %SageValue @sage_rt_gpu_create_descriptor_pool(%SageValue, %SageValue)
declare %SageValue @sage_rt_gpu_allocate_descriptor_set(%SageValue, %SageValue)
declare %SageValue @sage_rt_gpu_allocate_descriptor_sets(%SageValue, %SageValue, %SageValue)
declare %SageValue @sage_rt_gpu_update_descriptor(%SageValue, %SageValue, %SageValue, %SageValue)
declare %SageValue @sage_rt_gpu_update_descriptor_image(%SageValue, %SageValue, %SageValue, %SageValue, %SageValue)
declare %SageValue @sage_rt_gpu_update_descriptor_range(%SageValue, %SageValue, %SageValue, %SageValue)
declare %SageValue @sage_rt_gpu_create_pipeline_layout(%SageValue, %SageValue, %SageValue)
declare %SageValue @sage_rt_gpu_create_compute_pipeline(%SageValue, %SageValue)
declare %SageValue @sage_rt_gpu_create_graphics_pipeline(%SageValue)
declare %SageValue @sage_rt_gpu_destroy_pipeline(%SageValue)
declare %SageValue @sage_rt_gpu_create_pipeline_cache()
declare %SageValue @sage_rt_gpu_create_render_pass(%SageValue, %SageValue)
declare %SageValue @sage_rt_gpu_create_render_pass_mrt(%SageValue, %SageValue)
declare %SageValue @sage_rt_gpu_destroy_render_pass(%SageValue)
declare %SageValue @sage_rt_gpu_create_framebuffer(%SageValue, %SageValue, %SageValue, %SageValue)
declare %SageValue @sage_rt_gpu_destroy_framebuffer(%SageValue)
declare %SageValue @sage_rt_gpu_create_depth_buffer(%SageValue, %SageValue, %SageValue)
declare %SageValue @sage_rt_gpu_create_command_pool(%SageValue)
declare %SageValue @sage_rt_gpu_create_command_buffer(%SageValue)
declare %SageValue @sage_rt_gpu_create_secondary_command_buffer(%SageValue)
declare %SageValue @sage_rt_gpu_begin_commands(%SageValue)
declare %SageValue @sage_rt_gpu_begin_secondary(%SageValue, %SageValue, %SageValue, %SageValue)
declare %SageValue @sage_rt_gpu_end_commands(%SageValue)
declare %SageValue @sage_rt_gpu_cmd_bind_compute_pipeline(%SageValue, %SageValue)
declare %SageValue @sage_rt_gpu_cmd_bind_graphics_pipeline(%SageValue, %SageValue)
declare %SageValue @sage_rt_gpu_cmd_bind_descriptor_set(%SageValue, %SageValue, %SageValue, %SageValue)
declare %SageValue @sage_rt_gpu_cmd_dispatch(%SageValue, %SageValue, %SageValue, %SageValue)
declare %SageValue @sage_rt_gpu_cmd_dispatch_indirect(%SageValue, %SageValue, %SageValue)
declare %SageValue @sage_rt_gpu_cmd_push_constants(%SageValue, %SageValue, %SageValue, %SageValue)
declare %SageValue @sage_rt_gpu_cmd_begin_render_pass(%SageValue, %SageValue, %SageValue, %SageValue, %SageValue, %SageValue)
declare %SageValue @sage_rt_gpu_cmd_end_render_pass(%SageValue)
declare %SageValue @sage_rt_gpu_cmd_draw(%SageValue, %SageValue, %SageValue, %SageValue, %SageValue)
declare %SageValue @sage_rt_gpu_cmd_draw_indexed(%SageValue, %SageValue, %SageValue, %SageValue, %SageValue, %SageValue)
declare %SageValue @sage_rt_gpu_cmd_draw_indirect(%SageValue, %SageValue, %SageValue, %SageValue, %SageValue)
declare %SageValue @sage_rt_gpu_cmd_draw_indexed_indirect(%SageValue, %SageValue, %SageValue, %SageValue, %SageValue)
declare %SageValue @sage_rt_gpu_cmd_bind_vertex_buffer(%SageValue, %SageValue)
declare %SageValue @sage_rt_gpu_cmd_bind_vertex_buffers(%SageValue, %SageValue)
declare %SageValue @sage_rt_gpu_cmd_bind_index_buffer(%SageValue, %SageValue)
declare %SageValue @sage_rt_gpu_cmd_set_viewport(%SageValue, %SageValue, %SageValue, %SageValue, %SageValue, %SageValue, %SageValue)
declare %SageValue @sage_rt_gpu_cmd_set_scissor(%SageValue, %SageValue, %SageValue, %SageValue, %SageValue)
declare %SageValue @sage_rt_gpu_cmd_pipeline_barrier(%SageValue, %SageValue, %SageValue, %SageValue, %SageValue)
declare %SageValue @sage_rt_gpu_cmd_image_barrier(%SageValue, %SageValue, %SageValue, %SageValue, %SageValue, %SageValue, %SageValue, %SageValue)
declare %SageValue @sage_rt_gpu_cmd_copy_buffer(%SageValue, %SageValue, %SageValue, %SageValue)
declare %SageValue @sage_rt_gpu_cmd_copy_buffer_to_image(%SageValue, %SageValue, %SageValue, %SageValue, %SageValue)
declare %SageValue @sage_rt_gpu_cmd_execute_commands(%SageValue, %SageValue)
declare %SageValue @sage_rt_gpu_cmd_queue_transfer_barrier(%SageValue, %SageValue, %SageValue, %SageValue)
declare %SageValue @sage_rt_gpu_create_fence(%SageValue)
declare %SageValue @sage_rt_gpu_wait_fence(%SageValue, %SageValue)
declare %SageValue @sage_rt_gpu_reset_fence(%SageValue)
declare %SageValue @sage_rt_gpu_destroy_fence(%SageValue)
declare %SageValue @sage_rt_gpu_create_semaphore()
declare %SageValue @sage_rt_gpu_destroy_semaphore(%SageValue)
declare %SageValue @sage_rt_gpu_submit(%SageValue, %SageValue)
declare %SageValue @sage_rt_gpu_submit_compute(%SageValue, %SageValue)
declare %SageValue @sage_rt_gpu_submit_with_sync(%SageValue, %SageValue, %SageValue, %SageValue)
declare %SageValue @sage_rt_gpu_queue_wait_idle()
declare %SageValue @sage_rt_gpu_device_wait_idle()
declare %SageValue @sage_rt_gpu_create_window(%SageValue, %SageValue, %SageValue)
declare %SageValue @sage_rt_gpu_destroy_window()
declare %SageValue @sage_rt_gpu_window_should_close()
declare %SageValue @sage_rt_gpu_poll_events()
declare %SageValue @sage_rt_gpu_init_windowed(%SageValue, %SageValue, %SageValue, %SageValue)
declare %SageValue @sage_rt_gpu_init_opengl_windowed(%SageValue, %SageValue, %SageValue, %SageValue, %SageValue)
declare %SageValue @sage_rt_gpu_shutdown_windowed()
declare %SageValue @sage_rt_gpu_swapchain_image_count()
declare %SageValue @sage_rt_gpu_swapchain_format()
declare %SageValue @sage_rt_gpu_swapchain_extent()
declare %SageValue @sage_rt_gpu_acquire_next_image(%SageValue)
declare %SageValue @sage_rt_gpu_present(%SageValue, %SageValue)
declare %SageValue @sage_rt_gpu_create_swapchain_framebuffers(%SageValue)
declare %SageValue @sage_rt_gpu_create_swapchain_framebuffers_depth(%SageValue, %SageValue)
declare %SageValue @sage_rt_gpu_recreate_swapchain()
declare %SageValue @sage_rt_gpu_key_pressed(%SageValue)
declare %SageValue @sage_rt_gpu_key_down(%SageValue)
declare %SageValue @sage_rt_gpu_key_just_pressed(%SageValue)
declare %SageValue @sage_rt_gpu_key_just_released(%SageValue)
declare %SageValue @sage_rt_gpu_mouse_pos()
declare %SageValue @sage_rt_gpu_mouse_button(%SageValue)
declare %SageValue @sage_rt_gpu_mouse_just_pressed(%SageValue)
declare %SageValue @sage_rt_gpu_mouse_just_released(%SageValue)
declare %SageValue @sage_rt_gpu_mouse_delta()
declare %SageValue @sage_rt_gpu_scroll_delta()
declare %SageValue @sage_rt_gpu_set_cursor_mode(%SageValue)
declare %SageValue @sage_rt_gpu_get_time()
declare %SageValue @sage_rt_gpu_window_size()
declare %SageValue @sage_rt_gpu_set_title(%SageValue)
declare %SageValue @sage_rt_gpu_window_resized()
declare %SageValue @sage_rt_gpu_update_input()
declare %SageValue @sage_rt_gpu_text_input_available()
declare %SageValue @sage_rt_gpu_text_input_read()
declare %SageValue @sage_rt_gpu_load_texture(%SageValue, %SageValue, %SageValue, %SageValue)
declare %SageValue @sage_rt_gpu_texture_dims(%SageValue)
declare %SageValue @sage_rt_gpu_generate_mipmaps(%SageValue)
declare %SageValue @sage_rt_gpu_create_cubemap(%SageValue)
declare %SageValue @sage_rt_gpu_upload_device_local(%SageValue, %SageValue)
declare %SageValue @sage_rt_gpu_upload_bytes(%SageValue, %SageValue)
declare %SageValue @sage_rt_gpu_create_uniform_buffer(%SageValue)
declare %SageValue @sage_rt_gpu_update_uniform(%SageValue, %SageValue)
declare %SageValue @sage_rt_gpu_create_offscreen_target(%SageValue, %SageValue, %SageValue, %SageValue)
declare %SageValue @sage_rt_gpu_screenshot(%SageValue)
declare %SageValue @sage_rt_gpu_save_screenshot(%SageValue)
declare %SageValue @sage_rt_gpu_load_font(%SageValue, %SageValue)
declare %SageValue @sage_rt_gpu_font_atlas(%SageValue)
declare %SageValue @sage_rt_gpu_font_set_atlas(%SageValue, %SageValue, %SageValue)
declare %SageValue @sage_rt_gpu_font_text_verts(%SageValue, %SageValue, %SageValue, %SageValue, %SageValue)
declare %SageValue @sage_rt_gpu_font_measure(%SageValue, %SageValue, %SageValue)
declare %SageValue @sage_rt_gpu_load_gltf(%SageValue)
declare %SageValue @sage_rt_gpu_graphics_family()
declare %SageValue @sage_rt_gpu_compute_family()
declare %SageValue @sage_rt_gpu_set_platform(%SageValue)
declare %SageValue @sage_rt_gpu_get_platform()
declare %SageValue @sage_rt_gpu_detected_platform()

@counter = internal global %SageValue zeroinitializer
@answer = internal global %SageValue zeroinitializer

define %SageValue @sage_fn_fib(%SageValue %arg_n) {
entry:
  %n = alloca %SageValue
  store %SageValue %arg_n, %SageValue* %n
  %0 = load %SageValue, %SageValue* %n
  %1 = call %SageValue @sage_rt_number(double 1.00000000000000000e+00)
  %2 = call %SageValue @sage_rt_lte(%SageValue %0, %SageValue %1)
  %3 = call i32 @sage_rt_get_bool(%SageValue %2)
  %4 = icmp ne i32 %3, 0
  br i1 %4, label %L0, label %L2
L0:
  %5 = load %SageValue, %SageValue* %n
  ret %SageValue %5
L2:
  %6 = load %SageValue, %SageValue* %n
  %7 = call %SageValue @sage_rt_number(double 1.00000000000000000e+00)
  %8 = call %SageValue @sage_rt_sub(%SageValue %6, %SageValue %7)
  %9 = call %SageValue @sage_fn_fib(%SageValue %8)
  %10 = load %SageValue, %SageValue* %n
  %11 = call %SageValue @sage_rt_number(double 2.00000000000000000e+00)
  %12 = call %SageValue @sage_rt_sub(%SageValue %10, %SageValue %11)
  %13 = call %SageValue @sage_fn_fib(%SageValue %12)
  %14 = call %SageValue @sage_rt_add(%SageValue %9, %SageValue %13)
  ret %SageValue %14
}

define %SageValue @sage_fn_accumulate(%SageValue %arg_limit) {
entry:
  %limit = alloca %SageValue
  store %SageValue %arg_limit, %SageValue* %limit
  %total = alloca %SageValue
  %current = alloca %SageValue
  %0 = call %SageValue @sage_rt_number(double 0.00000000000000000e+00)
  store %SageValue %0, %SageValue* %total
  %1 = call %SageValue @sage_rt_number(double 1.00000000000000000e+00)
  store %SageValue %1, %SageValue* %current
  br label %L3
L3:
  %2 = load %SageValue, %SageValue* %current
  %3 = load %SageValue, %SageValue* %limit
  %4 = call %SageValue @sage_rt_lte(%SageValue %2, %SageValue %3)
  %5 = call i32 @sage_rt_get_bool(%SageValue %4)
  %6 = icmp ne i32 %5, 0
  br i1 %6, label %L4, label %L5
L4:
  %7 = load %SageValue, %SageValue* %total
  %8 = load %SageValue, %SageValue* %current
  %9 = call %SageValue @sage_rt_add(%SageValue %7, %SageValue %8)
  store %SageValue %9, %SageValue* %total
  %10 = load %SageValue, %SageValue* %current
  %11 = call %SageValue @sage_rt_number(double 1.00000000000000000e+00)
  %12 = call %SageValue @sage_rt_add(%SageValue %10, %SageValue %11)
  store %SageValue %12, %SageValue* %current
  br label %L3
L5:
  %13 = load %SageValue, %SageValue* %total
  ret %SageValue %13
}

define i32 @main() {
entry:
  %0 = call %SageValue @sage_rt_number(double 0.00000000000000000e+00)
  store %SageValue %0, %SageValue* @counter
  br label %L6
L6:
  %1 = load %SageValue, %SageValue* @counter
  %2 = call %SageValue @sage_rt_number(double 3.00000000000000000e+00)
  %3 = call %SageValue @sage_rt_lt(%SageValue %1, %SageValue %2)
  %4 = call i32 @sage_rt_get_bool(%SageValue %3)
  %5 = icmp ne i32 %4, 0
  br i1 %5, label %L7, label %L8
L7:
  %6 = load %SageValue, %SageValue* @counter
  %7 = call %SageValue @sage_rt_number(double 1.00000000000000000e+00)
  %8 = call %SageValue @sage_rt_add(%SageValue %6, %SageValue %7)
  store %SageValue %8, %SageValue* @counter
  br label %L6
L8:
  %9 = load %SageValue, %SageValue* @counter
  call void @sage_rt_print(%SageValue %9)
  %10 = call %SageValue @sage_rt_number(double 6.00000000000000000e+00)
  %11 = call %SageValue @sage_fn_fib(%SageValue %10)
  store %SageValue %11, %SageValue* @answer
  %12 = load %SageValue, %SageValue* @answer
  call void @sage_rt_print(%SageValue %12)
  %13 = call %SageValue @sage_rt_number(double 5.00000000000000000e+00)
  %14 = call %SageValue @sage_fn_accumulate(%SageValue %13)
  call void @sage_rt_print(%SageValue %14)
  %15 = getelementptr [5 x i8], [5 x i8]* @.str.0, i64 0, i64 0
  %16 = call %SageValue @sage_rt_string(i8* %15)
  %17 = call %SageValue @sage_rt_number(double 5.00000000000000000e+00)
  %18 = call %SageValue @sage_fn_fib(%SageValue %17)
  %19 = call %SageValue @sage_rt_str(%SageValue %18)
  %20 = call %SageValue @sage_rt_add(%SageValue %16, %SageValue %19)
  call void @sage_rt_print(%SageValue %20)
  %21 = load %SageValue, %SageValue* @answer
  %22 = call %SageValue @sage_rt_number(double 8.00000000000000000e+00)
  %23 = call %SageValue @sage_rt_eq(%SageValue %21, %SageValue %22)
  %24 = call i32 @sage_rt_get_bool(%SageValue %23)
  %25 = icmp ne i32 %24, 0
  br i1 %25, label %L9, label %L10
L9:
  %26 = getelementptr [11 x i8], [11 x i8]* @.str.1, i64 0, i64 0
  %27 = call %SageValue @sage_rt_string(i8* %26)
  call void @sage_rt_print(%SageValue %27)
  br label %L11
L10:
  %28 = getelementptr [12 x i8], [12 x i8]* @.str.2, i64 0, i64 0
  %29 = call %SageValue @sage_rt_string(i8* %28)
  call void @sage_rt_print(%SageValue %29)
  br label %L11
L11:
  ret i32 0
}

@.str.0 = private unnamed_addr constant [5 x i8] c"fib=\00"
@.str.1 = private unnamed_addr constant [11 x i8] c"phase10-ok\00"
@.str.2 = private unnamed_addr constant [12 x i8] c"phase10-bad\00"
