// Generated by Sage Kotlin Backend
// https://github.com/sageLang/sage
@file:Suppress("UNUSED_PARAMETER", "UNUSED_VARIABLE", "NAME_SHADOWING")

import sage.runtime.*
import sage.runtime.SageRuntime as S
import kotlinx.coroutines.*

typealias SageVal = SageRuntime.Value

suspend fun fetch_data(): SageVal {
    return S.num(42.0)
    return S.nil
}

suspend fun compute(x: SageVal): SageVal {
    return S.mul(x, S.num(2.0))
    return S.nil
}

fun main() {
    S.init()
    
    var result = kotlinx.coroutines.runBlocking { fetch_data() }
    S.printLn(result)
    var doubled = kotlinx.coroutines.runBlocking { compute(S.num(21.0)) }
    S.printLn(doubled)
    
}
