// Generated by Sage Kotlin Backend
// https://github.com/sageLang/sage
@file:Suppress("UNUSED_PARAMETER", "UNUSED_VARIABLE", "NAME_SHADOWING")

import sage.runtime.*
import sage.runtime.SageRuntime as S
import kotlinx.coroutines.*

typealias SageVal = SageRuntime.Value

fun main() {
    S.init()
    
    var x = S.num(10.0)
    var name = S.str("Sage")
    var flag = S.bool(true)
    var nothing = S.nil
    S.printLn(x)
    S.printLn(name)
    S.printLn(flag)
    S.printLn(nothing)
    var a = S.add(S.num(10.0), S.num(20.0))
    var b = S.mul(a, S.num(3.0))
    var c = S.div(b, S.num(2.0))
    var d = S.mod(S.num(100.0), S.num(7.0))
    S.printLn(a)
    S.printLn(b)
    S.printLn(c)
    S.printLn(d)
    var greeting = S.add(S.add(S.str("Hello, "), name), S.str("!"))
    S.printLn(greeting)
    S.printLn(S.len(greeting))
    S.printLn(S.gt(S.num(10.0), S.num(5.0)))
    S.printLn(S.eq(S.num(10.0), S.num(10.0)))
    S.printLn(S.neq(S.num(10.0), S.num(5.0)))
    S.printLn(S.lte(S.num(10.0), S.num(10.0)))
    S.printLn(S.and(S.bool(true), S.bool(false)))
    S.printLn(S.or(S.bool(true), S.bool(false)))
    S.printLn(S.not(S.bool(false)))
    S.printLn(S.str(S.num(42.0)))
    S.printLn(S.toNumber(S.str("3.14")))
    S.printLn(S.typeOf(S.num(42.0)))
    S.printLn(S.typeOf(S.str("hello")))
    
}
