// Generated by Sage Kotlin Backend
// https://github.com/sageLang/sage
@file:Suppress("UNUSED_PARAMETER", "UNUSED_VARIABLE", "NAME_SHADOWING")

import sage.runtime.*
import sage.runtime.SageRuntime as S
import kotlinx.coroutines.*

typealias SageVal = SageRuntime.Value

fun main() {
    S.init()
    
    var buf = S.memAlloc(S.num(256.0))
    S.memWrite(buf, S.num(0.0), S.str("int"), S.num(42.0))
    S.memWrite(buf, S.num(4.0), S.str("int"), S.num(100.0))
    S.memWrite(buf, S.num(8.0), S.str("double"), S.num(3.1400000000000001))
    var a = S.memRead(buf, S.num(0.0), S.str("int"))
    var b = S.memRead(buf, S.num(4.0), S.str("int"))
    var c = S.memRead(buf, S.num(8.0), S.str("double"))
    S.printLn(a)
    S.printLn(b)
    S.printLn(c)
    S.memFree(buf)
    var arch = S.str("jvm")
    S.printLn(arch)
    
}
