// Generated by Sage Kotlin Backend
// https://github.com/sageLang/sage
@file:Suppress("UNUSED_PARAMETER", "UNUSED_VARIABLE", "NAME_SHADOWING")

import sage.runtime.*
import sage.runtime.SageRuntime as S
import kotlinx.coroutines.*

typealias SageVal = SageRuntime.Value

fun main() {
    S.init()
    
    var x = S.num(10.0)
    var y = S.num(20.0)
    var sum = S.add(x, y)
    S.printLn(sum)
    var name = S.str("Sage")
    var flag = S.bool(true)
    var result = S.add(S.mul(x, y), S.num(5.0))
    S.printLn(result)
    var total = S.num(0.0)
    var i = S.num(0.0)
    while (S.truthy(S.lt(i, S.num(100.0)))) {
        total = S.add(total, i)
        i = S.add(i, S.num(1.0))
    }
    S.printLn(total)
    
}
