## ESP32 board support smoke test (host-runnable, no hardware needed).
##
## Run from the repo root:
##   SAGE_PATH=core/lib ./core/sage core/boards/ESP32/test_smoke.sage

import esp32

var failed = false

proc check(name, got, want):
    if got != want:
        print("FAIL", name, "got", got, "want", want)
        failed = true

check("chip", esp32.CHIP_NAME, "ESP32")
check("cores", esp32.CPU_CORES, 2)
check("freq", esp32.CPU_FREQ_MHZ, 240)
check("wifi-2.4-only", esp32.WIFI_SUPPORTS_5GHZ, false)
check("flash-size", esp32.FLASH_SIZE_BYTES, 4194304)
check("boot-offset", esp32.flash_offset("bootloader"), 4096)
check("part-offset", esp32.flash_offset("partitions"), 32768)
check("app-offset", esp32.flash_offset("app"), 65536)
check("unknown-region", esp32.flash_offset("nvs"), -1)
check("pin0-valid", esp32.pin_valid(0), true)
check("pin20-absent", esp32.pin_valid(20), false)
check("pin39-valid", esp32.pin_valid(39), true)
check("pin40-invalid", esp32.pin_valid(40), false)
check("pin2-output", esp32.pin_can_output(2), true)
check("pin34-no-output", esp32.pin_can_output(34), false)
check("pin34-input-only", esp32.pin_is_input_only(34), true)
check("pin2-not-input-only", esp32.pin_is_input_only(2), false)
check("pin0-strapping", esp32.pin_is_strapping(0), true)
check("pin1-not-strapping", esp32.pin_is_strapping(1), false)
check("pin6-flash", esp32.pin_is_flash(6), true)
check("pin2-not-flash", esp32.pin_is_flash(2), false)
check("adc1-32", esp32.adc1_capable(32), true)
check("adc1-27", esp32.adc1_capable(27), false)
check("dac-25", esp32.dac_capable(25), true)
check("dac-26", esp32.dac_capable(26), true)
check("dac-27", esp32.dac_capable(27), false)
check("boot-magic", esp32.boot_magic_ok(233), true)
check("boot-magic-bad", esp32.boot_magic_ok(0), false)
check("part-magic", esp32.part_magic_ok(170, 80), true)
check("part-magic-bad", esp32.part_magic_ok(0, 0), false)
check("flash-mode-dio", esp32.valid_flash_mode("dio"), true)
check("flash-mode-bogus", esp32.valid_flash_mode("sdio"), false)
check("uart0-tx", esp32.UART0_TX_PIN, 1)
check("uart0-rx", esp32.UART0_RX_PIN, 3)
check("adc1-ch36", esp32.adc1_channel(36), 0)
check("adc1-ch32", esp32.adc1_channel(32), 4)
check("adc1-ch39", esp32.adc1_channel(39), 3)
check("adc1-none", esp32.adc1_channel(27), -1)
check("adc-fs-0db", esp32.adc_fullscale_mv(0), 1100)
check("adc-fs-11db", esp32.adc_fullscale_mv(11), 3900)
check("adc-fs-bad", esp32.adc_fullscale_mv(3), -1)
check("adc-conv-full", esp32.adc_to_mv(4095, 11), 3900)
check("adc-conv-zero", esp32.adc_to_mv(0, 11), 0)
check("adc-conv-bad-raw", esp32.adc_to_mv(-1, 11), -1)
check("adc-conv-bad-atten", esp32.adc_to_mv(100, 3), -1)
check("touch-t0", esp32.touch_channel(4), 0)
check("touch-t9", esp32.touch_channel(32), 9)
check("touch-none", esp32.touch_channel(5), -1)
check("rtc-0", esp32.rtc_capable(0), true)
check("rtc-25", esp32.rtc_capable(25), true)
check("rtc-5", esp32.rtc_capable(5), false)
check("pwm-full", esp32.pwm_duty(100, 8), 255)
check("pwm-zero", esp32.pwm_duty(0, 8), 0)
check("pwm-half", esp32.pwm_duty(50, 8), 127)
check("pwm-over", esp32.pwm_duty(150, 8), 255)
check("uart1-remap", esp32.uart_needs_remap(1), true)
check("uart0-no-remap", esp32.uart_needs_remap(0), false)
check("uart2-no-remap", esp32.uart_needs_remap(2), false)
check("uart2-pins", esp32.UART2_DEFAULT_TX, 17)
check("img-size-ok", esp32.image_size_ok(1810976), true)
check("img-size-zero", esp32.image_size_ok(0), false)
check("img-size-huge", esp32.image_size_ok(4194305), false)
check("i2c-count", esp32.I2C_COUNT, 2)
check("i2c-defaults", esp32.I2C_SDA_PIN, 21)
check("i2c-scl", esp32.I2C_SCL_PIN, 22)
check("i2c-addr-ok", esp32.i2c_addr_usable(72), true)
check("i2c-addr-reserved-low", esp32.i2c_addr_usable(3), false)
check("i2c-addr-reserved-high", esp32.i2c_addr_usable(120), false)
check("i2c-freq-400k", esp32.i2c_freq_ok(400000), true)
check("i2c-freq-bad", esp32.i2c_freq_ok(50000), false)
check("atten-1v", esp32.adc_atten_for_voltage(900), 0)
check("atten-3v3", esp32.adc_atten_for_voltage(3300), 11)
check("atten-too-high", esp32.adc_atten_for_voltage(5000), -1)
check("ext1-single", esp32.ext1_mask([0]), 1)
check("ext1-pair", esp32.ext1_mask([0, 2]), 5)
check("ext1-bad", esp32.ext1_mask([0, 5]), -1)
check("batt-sane", esp32.battery_hours(1000, 10, 100, 36) > 100, true)
check("batt-bad", esp32.battery_hours(0, 10, 100, 36), -1)
check("wifi-ssid-ok", esp32.wifi_ssid_ok("HomeNet"), true)
check("wifi-ssid-empty", esp32.wifi_ssid_ok(""), false)
check("wifi-pass-open", esp32.wifi_pass_ok(""), true)
check("wifi-pass-short", esp32.wifi_pass_ok("abc"), false)
check("wifi-pass-ok", esp32.wifi_pass_ok("correct-horse-1"), true)
check("wifi-sta-ok", esp32.wifi_sta_ok("HomeNet", "correct-horse-1"), true)
check("wifi-sta-bad", esp32.wifi_sta_ok("HomeNet", "abc"), false)
check("wifi-ch-6", esp32.wifi_channel_ok(6), true)
check("wifi-ch-14", esp32.wifi_channel_ok(14), false)
check("wifi-auth", esp32.wifi_auth_ok("WPA2-PSK"), true)
check("wifi-auth-bad", esp32.wifi_auth_ok("WPA3-PSK"), false)
check("nvs-ns-ok", esp32.nvs_namespace_ok("sensor"), true)
check("nvs-ns-empty", esp32.nvs_namespace_ok(""), false)
check("nvs-key-ok", esp32.nvs_key_ok("boot_count"), true)
check("nvs-type-str", esp32.nvs_type_ok("str"), true)
check("nvs-type-bad", esp32.nvs_type_ok("float"), false)

if failed:
    print("SMOKE FAIL")
else:
    print("ALL OK: ESP32 board support")
    print(esp32.describe())
