gc_disable()
# SageLLM Chatbot - Compiled Binary
# Auto-generated by build_sagellm.sage

import io
import chat.bot
import chat.persona
import chat.session
import llm.engram

let memory = engram.create(nil)
memory["working_capacity"] = 20
engram.store_semantic(memory, "Sage is an indentation-based systems programming language built in C", 1.0)
engram.store_semantic(memory, "113 library modules across 11 subdirectories (graphics, os, net, crypto, ml, cuda, std, llm, agent, chat)", 1.0)
engram.store_semantic(memory, "Concurrent tri-color mark-sweep GC with SATB write barriers, sub-millisecond STW pauses", 1.0)
engram.store_semantic(memory, "3 compiler backends: C codegen, LLVM IR, native assembly (x86-64, aarch64, rv64)", 1.0)
engram.store_semantic(memory, "Dotted imports: import os.fat resolves to lib/os/fat.sage, binds as fat", 1.0)
engram.store_semantic(memory, "0 is TRUTHY in Sage - only false and nil are falsy", 1.0)
engram.store_semantic(memory, "No escape sequences - use chr(10) for newline, chr(34) for double-quote", 1.0)
engram.store_semantic(memory, "elif chains with 5+ branches malfunction - use sequential if/continue", 1.0)
engram.store_semantic(memory, "Class methods cannot see module-level let vars - pass as args or hardcode", 1.0)
engram.store_semantic(memory, "match is a reserved keyword", 1.0)
engram.store_semantic(memory, "Native ML backend: ml_native module with matmul, softmax, cross_entropy, adam_update", 1.0)
engram.store_semantic(memory, "Engram 4-tier memory: working (FIFO), episodic (timestamped), semantic (permanent), procedural (skills)", 1.0)
engram.store_semantic(memory, "Agent ReAct loop: observe -> think -> act -> reflect, with TOOL:/ANSWER: parsing", 1.0)
engram.store_semantic(memory, "Chatbot framework: intents, personas (SageDev/Teacher/Debugger), sessions, middleware", 1.0)
engram.store_semantic(memory, "Library paths: CWD, ./lib, source dir, /usr/local/share/sage/lib, SAGE_PATH env var", 1.0)
engram.store_semantic(memory, "Build: make (Makefile) or cmake -B build -DBUILD_SAGE=ON", 1.0)
engram.store_semantic(memory, "Tests: bash tests/run_tests.sh (224 tests), make test, make test-selfhost", 1.0)
engram.store_semantic(memory, "All self-hosted and heavy-allocation modules start with gc_disable()", 1.0)
engram.store_semantic(memory, "Version: 1.0.0 across REPL, sys.version, CMakeLists.txt, VSCode extension", 1.0)

proc contains(h, n):
    if len(n) > len(h):
        return false
    for i in range(len(h) - len(n) + 1):
        let found = true
        for j in range(len(n)):
            if not found:
                j = len(n)
            if found and h[i + j] != n[j]:
                found = false
        if found:
            return true
    return false

proc to_lower(s):
    let r = ""
    for i in range(len(s)):
        let c = ord(s[i])
        if c >= 65 and c <= 90:
            r = r + chr(c + 32)
        else:
            r = r + s[i]
    return r

proc sage_llm(prompt):
    let lp = to_lower(prompt)
    let ctx = engram.build_context(memory, lp, 3)
    if contains(lp, "for loop") or contains(lp, "iteration"):
        return "In Sage, use for loops:" + chr(10) + "  for i in range(10):" + chr(10) + "      print i"
    if contains(lp, "import") or contains(lp, "module"):
        return "Dotted imports: import os.fat, import net.url, import std.regex"
    if contains(lp, "class"):
        return "Classes: class Name: with proc init(self): and methods"
    if contains(lp, "gc") or contains(lp, "garbage"):
        return "Concurrent tri-color mark-sweep GC with SATB write barriers"
    if contains(lp, "help"):
        return "Ask about: for loops, imports, classes, GC, arrays, functions, compile"
    if len(ctx) > 0:
        return ctx
    return "I am SageDev. Ask me about Sage programming."

let b = bot.create("", "", sage_llm)
persona.apply_persona(b, persona.sage_developer())

proc on_greet(msg, conv):
    return "Hello, I am SageDev. Ask me anything about Sage."
proc on_bye(msg, conv):
    return "Goodbye. Happy coding."
bot.add_intent(b, "greet", ["hello", "hi", "hey"], on_greet)
bot.add_intent(b, "bye", ["bye", "quit", "exit"], on_bye)

let store = session.create_store()
let sess = session.new_session(store, "SageDev")

print "SageLLM Chatbot v1.0.0"
print bot.greet(b)
print "Type quit to exit."
print ""

let running = true
while running:
    let msg = input("You> ")
    if msg == "quit" or msg == "exit":
        running = false
        print bot.farewell(b)
    if running:
        engram.store_working(memory, msg, 0.7)
        let resp = bot.respond(b, msg)
        print ""
        print "SageDev> " + resp
        print ""
        session.add_turn(sess, msg, resp)
