gc_disable()
# SageLLM Chatbot v2.0.0 - Medium Model, 16K Context, All Features
# Auto-generated by build_sagellm.sage
# Run: sage models/sagellm_chatbot.sage

import io
import chat.bot
import chat.persona
import chat.session
import llm.engram
import llm.rag
import llm.prompt
import agent.planner
import agent.critic
import agent.grammar
import agent.semantic_router
import agent.trace
import agent.tot
import agent.schema

proc contains(h, n):
    if len(n) > len(h):
        return false
    for i in range(len(h) - len(n) + 1):
        let f = true
        for j in range(len(n)):
            if not f:
                j = len(n)
            if f and h[i + j] != n[j]:
                f = false
        if f:
            return true
    return false

proc to_lower(s):
    let r = ""
    for i in range(len(s)):
        let c = ord(s[i])
        if c >= 65 and c <= 90:
            r = r + chr(c + 32)
        else:
            r = r + s[i]
    return r

proc starts_with(s, prefix):
    if len(prefix) > len(s):
        return false
    for i in range(len(prefix)):
        if s[i] != prefix[i]:
            return false
    return true

proc substr(s, start, count):
    let r = ""
    let end = start + count
    if end > len(s):
        end = len(s)
    for i in range(end - start):
        r = r + s[start + i]
    return r

let memory = engram.create(nil)
memory["working_capacity"] = 30
memory["max_episodic"] = 10000
memory["max_semantic"] = 5000
engram.store_semantic(memory, "Sage is an indentation-based systems programming language built in C with self-hosted compiler", 1.0)
engram.store_semantic(memory, "127+ library modules across 11 subdirectories: graphics, os, net, crypto, ml, cuda, std, llm, agent, chat", 1.0)
engram.store_semantic(memory, "Concurrent tri-color mark-sweep GC with SATB write barriers and sub-millisecond STW pauses", 1.0)
engram.store_semantic(memory, "3 compiler backends: C codegen (--compile), LLVM IR (--compile-llvm), native assembly (--compile-native)", 1.0)
engram.store_semantic(memory, "Dotted imports: import os.fat resolves to lib/os/fat.sage", 1.0)
engram.store_semantic(memory, "0 is TRUTHY - only false and nil are falsy", 1.0)
engram.store_semantic(memory, "No escape sequences - use chr(10) for newline, chr(34) for double-quote", 1.0)
engram.store_semantic(memory, "elif chains with 5+ branches malfunction - use if/continue instead", 1.0)
engram.store_semantic(memory, "Class methods cannot see module-level let vars", 1.0)
engram.store_semantic(memory, "match is a reserved keyword", 1.0)
engram.store_semantic(memory, "Lexer produces INDENT/DEDENT tokens", 1.0)
engram.store_semantic(memory, "Parser is recursive descent in compiler.c", 1.0)
engram.store_semantic(memory, "AST: Expr and Stmt nodes in ast.h", 1.0)
engram.store_semantic(memory, "Tree-walking interpreter (interpreter.c)", 1.0)
engram.store_semantic(memory, "Values: numbers, strings, bools, nil, arrays, dicts, closures", 1.0)
engram.store_semantic(memory, "GC 4 phases: root scan, concurrent mark, remark, concurrent sweep", 1.0)
engram.store_semantic(memory, "Write barriers in env.c and value.c", 1.0)
engram.store_semantic(memory, "gc_disable() for heavy-allocation modules", 1.0)
engram.store_semantic(memory, "Native ML: matmul, softmax, cross_entropy, adam_update, rms_norm, silu, gelu at 12+ GFLOPS", 1.0)
engram.store_semantic(memory, "LLM library: 15 modules for building language models", 1.0)
engram.store_semantic(memory, "SageGPT: SwiGLU + RoPE + RMSNorm (Llama-style)", 1.0)
engram.store_semantic(memory, "LoRA for fine-tuning, DPO for alignment", 1.0)
engram.store_semantic(memory, "Engram: 4-tier memory with consolidation and decay", 1.0)
engram.store_semantic(memory, "RAG with keyword extraction and chunking", 1.0)
engram.store_semantic(memory, "GGUF export/import for Ollama and llama.cpp", 1.0)
engram.store_semantic(memory, "Quantization: int8/int4 with per-group scaling", 1.0)
engram.store_semantic(memory, "Agent ReAct loop: observe, think, act, reflect", 1.0)
engram.store_semantic(memory, "Supervisor-Worker architecture", 1.0)
engram.store_semantic(memory, "Critic/validator: rule-based + LLM critics", 1.0)
engram.store_semantic(memory, "Grammar-constrained decoding", 1.0)
engram.store_semantic(memory, "Tree of Thoughts: MCTS-style search", 1.0)
engram.store_semantic(memory, "Semantic routing: fast keyword dispatch", 1.0)
engram.store_semantic(memory, "SFT trace recording", 1.0)
engram.store_semantic(memory, "Schema-validated tool calls", 1.0)
engram.store_semantic(memory, "Task planner: dependency DAG", 1.0)
engram.store_semantic(memory, "6 personas: SageDev, CodeReviewer, Teacher, Debugger, Architect, Assistant", 1.0)
engram.store_semantic(memory, "Sessions: multi-session with history export", 1.0)
engram.store_semantic(memory, "Vulkan engine: 24 modules, PBR, deferred, SSAO, SSR, TAA", 1.0)
engram.store_semantic(memory, "OpenGL 4.5 backend", 1.0)
engram.store_semantic(memory, "OS dev: 15 modules (FAT, ELF, PE, MBR, GPT, PCI, ACPI, UEFI, paging, IDT)", 1.0)
engram.store_semantic(memory, "Networking: socket, tcp, http, ssl + 8 lib/net modules", 1.0)
engram.store_semantic(memory, "Crypto: SHA-256, HMAC, Base64, RC4, PBKDF2 (6 modules)", 1.0)
engram.store_semantic(memory, "Std: regex, datetime, log, argparse, fmt, testing, enum, trait, channel (23 modules)", 1.0)
engram.store_semantic(memory, "Build: make or cmake. Version 1.0.0", 1.0)
engram.store_semantic(memory, "Tests: 1567+ self-hosted, 144 interpreter, 28 compiler", 1.0)
engram.store_semantic(memory, "Library search: CWD, ./lib, installed, SAGE_PATH, exe-relative", 1.0)
engram.store_semantic(memory, "CUDA: device, memory, kernel, stream", 1.0)
engram.store_semantic(memory, "ML: tensor, nn, optim, loss, data, debug, viz, monitor", 1.0)
engram.store_semantic(memory, "Graphics: scene, gltf 2.0, material, asset cache, frame graph", 1.0)
engram.store_semantic(memory, "GGUF import: convert Ollama/llama.cpp models to SageGPT format", 1.0)
engram.store_procedural(memory, "write_sage_code", ["proc for functions", "let for variables", "import os.fat", "gc_disable()", "chr(10) for newline"], 1.0)
engram.store_procedural(memory, "debug_sage", ["gc_disable()", "avoid match", "chr() not escapes"], 1.0)
engram.store_procedural(memory, "compile_sage", ["--compile", "--compile-llvm", "--compile-native"], 1.0)

let rag_store = rag.create_store()
let rag_files = ["documentation/SageLang_Guide.md", "documentation/GC_Guide.md", "documentation/LLM_Guide.md", "documentation/Agent_Chat_Guide.md", "documentation/StdLib_Guide.md"]
for i in range(len(rag_files)):
    let content = io.readfile(rag_files[i])
    if content != nil:
        let meta = {}
        meta["source"] = rag_files[i]
        rag.add_document(rag_store, content, meta)

let router = semantic_router.create_router(2)
semantic_router.add_sage_routes(router)
let recorder = trace.create_recorder()
let validator = critic.create_validator()
critic.add_rule(validator, "not_empty", critic.rule_not_empty)

proc reason(question):
    let chain = {}
    chain["steps"] = []
    chain["conclusion"] = ""
    let lp = to_lower(question)
    let fast = semantic_router.route(router, lp)
    if fast["routed"]:
        push(chain["steps"], "Fast-routed")
        chain["conclusion"] = fast["result"]
        return chain
    let mem_results = engram.recall(memory, lp, 5)
    if len(mem_results) > 0:
        let mt = ""
        for i in range(len(mem_results)):
            mt = mt + mem_results[i]["entry"]["content"]
            if i < len(mem_results) - 1:
                mt = mt + "; "
        push(chain["steps"], "Recalled: " + mt)
    let rag_ctx = rag.build_context(rag_store, lp, 3)
    if len(rag_ctx) > 0:
        push(chain["steps"], "RAG: " + str(len(rag_ctx)) + " chars")
    let topic = "general"
    if topic == "general":
        if contains(lp, "llm") or contains(lp, "language model") or contains(lp, "transformer") or contains(lp, "lora") or contains(lp, "engram") or contains(lp, "neural") or contains(lp, "tokeniz"):
            topic = "llm"
    if topic == "general":
        if contains(lp, "agent") or contains(lp, "react") or contains(lp, "supervisor") or contains(lp, "tool use"):
            topic = "agent"
    if topic == "general":
        if contains(lp, "chatbot") or contains(lp, "persona") or contains(lp, "conversation") or contains(lp, "intent"):
            topic = "chatbot"
    if topic == "general":
        if contains(lp, "crypto") or contains(lp, "sha") or contains(lp, "hash") or contains(lp, "encrypt"):
            topic = "crypto"
    if topic == "general":
        if contains(lp, "network") or contains(lp, "http") or contains(lp, "socket") or contains(lp, "url") or contains(lp, "dns"):
            topic = "networking"
    if topic == "general":
        if contains(lp, "baremetal") or contains(lp, "uefi") or contains(lp, "kernel") or contains(lp, "elf") or contains(lp, "pci") or contains(lp, "osdev"):
            topic = "osdev"
    if topic == "general":
        if contains(lp, "tensor") or contains(lp, "machine learn") or contains(lp, "training") or contains(lp, "gradient"):
            topic = "ml"
    if topic == "general":
        if contains(lp, "gpu") or contains(lp, "vulkan") or contains(lp, "opengl") or contains(lp, "shader") or contains(lp, "render"):
            topic = "graphics"
    if topic == "general":
        if contains(lp, "regex") or contains(lp, "regular exp"):
            topic = "regex"
    if topic == "general":
        if contains(lp, "gc ") or contains(lp, "garbage"):
            topic = "gc"
    if topic == "general":
        if contains(lp, "compile") or contains(lp, "backend") or contains(lp, "emit"):
            topic = "compiler"
    if topic == "general":
        if contains(lp, "for ") or contains(lp, "loop") or contains(lp, "while"):
            topic = "loops"
    if topic == "general":
        if contains(lp, "import") or contains(lp, "module") or contains(lp, "library"):
            topic = "modules"
    if topic == "general":
        if contains(lp, "class ") or contains(lp, "object") or contains(lp, "inherit"):
            topic = "oop"
    if topic == "general":
        if contains(lp, "array") or contains(lp, "dict") or contains(lp, "data struct"):
            topic = "data"
    if topic == "general":
        if contains(lp, "function") or contains(lp, "proc ") or contains(lp, "closure"):
            topic = "functions"
    if topic == "general":
        if contains(lp, "error") or contains(lp, "exception") or contains(lp, "try "):
            topic = "errors"
    if topic == "general":
        if contains(lp, "test") or contains(lp, "debug") or contains(lp, "bug"):
            topic = "testing"
    if topic == "general":
        if contains(lp, "thread") or contains(lp, "async") or contains(lp, "channel") or contains(lp, "concurrent"):
            topic = "concurrency"
    if topic == "general":
        if contains(lp, "plan ") or contains(lp, "how to build") or contains(lp, "steps"):
            topic = "planning"
    push(chain["steps"], "Topic: " + topic)
    let answer = ""
    if topic == "llm":
        answer = "LLM library (15 modules): config, tokenizer, embedding, attention, transformer, generate, train, agent, prompt, lora, quantize, engram, rag, dpo, gguf. SageGPT: SwiGLU+RoPE+RMSNorm. Native C backend at 12+ GFLOPS."
    if topic == "agent":
        answer = "Agent framework (12 modules): core (ReAct), tools, planner (DAG), router, supervisor (workers), critic, schema, trace (SFT), grammar (constrained decoding), sandbox, tot (Tree of Thoughts), semantic_router."
    if topic == "chatbot":
        answer = "Chat framework: bot (intents, middleware), persona (6: SageDev, CodeReviewer, Teacher, Debugger, Architect, Assistant), session (history, export)."
    if topic == "crypto":
        answer = "Crypto (6 modules): hash (SHA-256, SHA-1, CRC-32), hmac, encoding (Base64, hex), cipher (XOR, RC4, CBC/CTR), rand (xoshiro256**, UUID v4), password (PBKDF2)."
    if topic == "networking":
        answer = "Networking: native (socket, tcp, http, ssl) + lib/net/ (8): url, headers, request, server, websocket, mime, dns, ip."
    if topic == "osdev":
        answer = "OS dev (15 modules): fat, elf, pe, mbr, gpt, pci, acpi, uefi, paging, idt, serial, dtb, alloc, vfs."
    if topic == "ml":
        answer = "ML: tensor, nn, optim, loss, data, debug, viz, monitor + cuda. Native: matmul, softmax, RMSNorm, Adam at 12+ GFLOPS."
    if topic == "graphics":
        answer = "GPU engine (24 modules): Vulkan + OpenGL 4.5. vulkan, gpu, math3d, mesh, renderer, pbr, shadows, deferred (SSAO, SSR), taa, postprocess, scene, gltf, material."
    if topic == "regex":
        answer = "Regex (std.regex): test(), search(), find_all(), replace_all(), split_by(). Supports . * + ? [] [^] ^ $ |."
    if topic == "gc":
        answer = "Tri-color GC: root scan (STW), concurrent mark, remark (STW), concurrent sweep. SATB write barrier. gc_collect(), gc_enable(), gc_disable()."
    if topic == "compiler":
        answer = "3 backends: --compile (C), --compile-llvm, --compile-native (x86-64/aarch64/rv64). Optimize: -O0 to -O3."
    if topic == "loops":
        answer = "Loops: for i in range(10): body. for item in array: body. while cond: body. break/continue."
    if topic == "modules":
        answer = "11 categories: os(15), net(8), crypto(6), ml(8), cuda(4), std(23), llm(15), agent(12), chat(3), graphics(24), root(9). 127+ total."
    if topic == "oop":
        answer = "OOP: class Name: with proc init(self): and methods. Inheritance: class Dog(Animal):."
    if topic == "data":
        answer = "Arrays: [1,2,3], push(), pop(), slicing. Dicts: {}, d[key]=val, dict_keys(), dict_values(). Tuples: (1,2,3)."
    if topic == "functions":
        answer = "proc name(args): body. Return values. Closures capture outer vars. First-class functions."
    if topic == "errors":
        answer = "try: risky. catch e: handle. finally: cleanup. raise to throw."
    if topic == "testing":
        answer = "Tests: run_tests.sh (144), make test (28), make test-selfhost (1567+). Debug: gc_disable(), chr()."
    if topic == "concurrency":
        answer = "Concurrency: thread, async/await, std.channel, std.atomic, std.rwlock, std.condvar, std.threadpool."
    if topic == "planning":
        answer = "Plan: 1) Define goal, 2) Create module, 3) Implement, 4) Test, 5) Document, 6) Run tests."
    if len(answer) == 0:
        if len(mem_results) > 0:
            answer = "Based on my knowledge: " + mem_results[0]["entry"]["content"]
        else:
            answer = "I can help with: loops, imports, classes, GC, compiler, data, functions, errors, testing, concurrency, planning, LLM, agents, chatbot, crypto, networking, OS dev, ML, graphics, regex."
    push(chain["steps"], "Answering about " + topic)
    chain["conclusion"] = answer
    engram.store_episodic(memory, "Answered: " + topic, 0.6)
    trace.record_thought(recorder, "Topic: " + topic)
    trace.record_output(recorder, answer)
    return chain

proc chain_to_string(chain):
    let result = ""
    let steps = chain["steps"]
    for i in range(len(steps)):
        result = result + "  Thought " + str(i + 1) + ": " + steps[i] + chr(10)
    result = result + chr(10) + "  Answer: " + chain["conclusion"]
    return result

proc sage_llm(p):
    return reason(p)["conclusion"]

let b = bot.create("", "", sage_llm)
persona.apply_persona(b, persona.sage_developer())
proc on_greet(msg, conv):
    return "Hello! SageDev v2.0 with CoT, 4-tier memory, RAG, semantic routing, grammar validation, planning."
proc on_bye(msg, conv):
    engram.consolidate(memory)
    return "Goodbye. Memory consolidated."
proc on_help(msg, conv):
    return "Commands: quit, memory, remember <fact>, recall <query>, think <q>, plan <goal>, review <code>, trace, personas, help"
bot.add_intent(b, "greet", ["hello", "hi", "hey"], on_greet)
bot.add_intent(b, "bye", ["bye", "quit", "exit"], on_bye)
bot.add_intent(b, "help", ["help", "commands", "?"], on_help)
let store = session.create_store()
let sess = session.new_session(store, "SageDev")
let current_persona = "SageDev"

print "============================================"
print "  SageLLM Chatbot v2.0.0 (Medium | 16K)"
print "  SageGPT: SwiGLU + RoPE + RMSNorm"
print "  CoT + Engram + RAG + Routing + Grammar"
print "============================================"
print bot.greet(b)
print "Commands: quit, memory, remember, recall, think, plan, review, trace, personas, help"
print ""
let running = true
while running:
    let msg = input("You> ")
    if msg == "quit" or msg == "exit":
        running = false
        engram.consolidate(memory)
        print "SageDev> Goodbye. Memory consolidated."
    if running and msg == "memory":
        print engram.summary(memory)
    if running and starts_with(msg, "remember "):
        engram.store_semantic(memory, substr(msg, 9, len(msg) - 9), 0.8)
        print "Remembered."
    if running and starts_with(msg, "recall "):
        let results = engram.recall(memory, substr(msg, 7, len(msg) - 7), 5)
        if len(results) > 0:
            for i in range(len(results)):
                print "  [" + str(i + 1) + "] " + results[i]["entry"]["content"]
        else:
            print "  No memories found."
    if running and starts_with(msg, "think "):
        trace.begin_trace(recorder, substr(msg, 6, len(msg) - 6))
        print chain_to_string(reason(substr(msg, 6, len(msg) - 6)))
        trace.end_trace(recorder, true)
    if running and starts_with(msg, "plan "):
        let goal = substr(msg, 5, len(msg) - 5)
        let plan = planner.create_plan(goal)
        planner.add_step(plan, "Analyze", "", "", nil)
        planner.add_step(plan, "Design", "", "", [0])
        planner.add_step(plan, "Implement", "", "", [1])
        planner.add_step(plan, "Test", "", "", [2])
        planner.add_step(plan, "Document", "", "", [3])
        print planner.format_plan(plan)
        engram.store_episodic(memory, "Plan: " + goal, 0.8)
    if running and starts_with(msg, "review "):
        let v = grammar.validate_sage_code(substr(msg, 7, len(msg) - 7))
        if v["valid"]:
            print "  Code valid!"
        else:
            let errs = v["errors"]
            for i in range(len(errs)):
                print "  - " + errs[i]
    if running and msg == "trace":
        let ts = trace.stats(recorder)
        print "  Traces: " + str(ts["total_traces"]) + " Steps: " + str(ts["total_steps"])
    if running and msg == "personas":
        print "  sagedev, teacher, debugger, architect"
    if running and msg == "teacher":
        persona.apply_persona(b, persona.teacher())
        current_persona = "Teacher"
        print "Switched to Teacher."
    if running and msg == "debugger":
        persona.apply_persona(b, persona.debugger())
        current_persona = "Debugger"
        print "Switched to Debugger."
    if running and msg == "architect":
        persona.apply_persona(b, persona.architect())
        current_persona = "Architect"
        print "Switched to Architect."
    if running and msg == "sagedev":
        persona.apply_persona(b, persona.sage_developer())
        current_persona = "SageDev"
        print "Switched to SageDev."
    if running and msg != "quit" and msg != "exit" and msg != "memory" and msg != "trace" and msg != "personas" and msg != "help" and msg != "?" and msg != "teacher" and msg != "debugger" and msg != "architect" and msg != "sagedev":
        let is_cmd = false
        if starts_with(msg, "think "):
            is_cmd = true
        if starts_with(msg, "plan "):
            is_cmd = true
        if starts_with(msg, "review "):
            is_cmd = true
        if starts_with(msg, "remember "):
            is_cmd = true
        if starts_with(msg, "recall "):
            is_cmd = true
        if not is_cmd:
            engram.store_working(memory, msg, 0.7)
            trace.begin_trace(recorder, msg)
            let resp = bot.respond(b, msg)
            trace.record_output(recorder, resp)
            trace.end_trace(recorder, true)
            let ctx = {}
            ctx["task"] = msg
            critic.validate(validator, resp, ctx)
            print ""
            print current_persona + "> " + resp
            print ""
            session.add_turn(sess, msg, resp)
