gc_disable()
# SageLLM Chatbot v1.0.0 with Chain-of-Thought, Engram Memory, Planning
# Auto-generated by build_sagellm.sage

import chat.bot
import chat.persona
import chat.session
import llm.engram
import llm.agent
import agent.core
import agent.planner

proc contains(h, n):
    if len(n) > len(h):
        return false
    for i in range(len(h) - len(n) + 1):
        let f = true
        for j in range(len(n)):
            if not f:
                j = len(n)
            if f and h[i + j] != n[j]:
                f = false
        if f:
            return true
    return false

proc to_lower(s):
    let r = ""
    for i in range(len(s)):
        let c = ord(s[i])
        if c >= 65 and c <= 90:
            r = r + chr(c + 32)
        else:
            r = r + s[i]
    return r

let memory = engram.create(nil)
memory["working_capacity"] = 20
memory["max_episodic"] = 5000
memory["max_semantic"] = 2000

engram.store_semantic(memory, "Sage is an indentation-based systems programming language built in C", 1.0)
engram.store_semantic(memory, "113 library modules across 11 subdirectories (graphics, os, net, crypto, ml, cuda, std, llm, agent, chat)", 1.0)
engram.store_semantic(memory, "Concurrent tri-color mark-sweep GC with SATB write barriers, sub-millisecond STW pauses", 1.0)
engram.store_semantic(memory, "3 compiler backends: C codegen, LLVM IR, native assembly (x86-64, aarch64, rv64)", 1.0)
engram.store_semantic(memory, "Dotted imports: import os.fat resolves to lib/os/fat.sage, binds as fat", 1.0)
engram.store_semantic(memory, "0 is TRUTHY in Sage - only false and nil are falsy", 1.0)
engram.store_semantic(memory, "No escape sequences - use chr(10) for newline, chr(34) for double-quote", 1.0)
engram.store_semantic(memory, "elif chains with 5+ branches malfunction - use sequential if/continue", 1.0)
engram.store_semantic(memory, "Class methods cannot see module-level let vars - pass as args or hardcode", 1.0)
engram.store_semantic(memory, "match is a reserved keyword", 1.0)
engram.store_semantic(memory, "Native ML backend: ml_native module with matmul, softmax, cross_entropy, adam_update", 1.0)
engram.store_semantic(memory, "Engram 4-tier memory: working (FIFO), episodic (timestamped), semantic (permanent), procedural (skills)", 1.0)
engram.store_semantic(memory, "Agent ReAct loop: observe -> think -> act -> reflect, with TOOL:/ANSWER: parsing", 1.0)
engram.store_semantic(memory, "Chatbot framework: intents, personas (SageDev/Teacher/Debugger), sessions, middleware", 1.0)
engram.store_semantic(memory, "Library paths: CWD, ./lib, source dir, /usr/local/share/sage/lib, SAGE_PATH env var", 1.0)
engram.store_semantic(memory, "Build: make (Makefile) or cmake -B build -DBUILD_SAGE=ON", 1.0)
engram.store_semantic(memory, "Tests: bash tests/run_tests.sh (224 tests), make test, make test-selfhost", 1.0)
engram.store_semantic(memory, "All self-hosted and heavy-allocation modules start with gc_disable()", 1.0)
engram.store_semantic(memory, "Version: 1.0.0 across REPL, sys.version, CMakeLists.txt, VSCode extension", 1.0)

# Chain-of-thought reasoning
proc reason(question):
    let chain = agent.create_reasoning_chain()
    let lp = to_lower(question)
    # Step 1: Recall relevant memory
    let mem_results = engram.recall(memory, lp, 5)
    if len(mem_results) > 0:
        let mem_text = ""
        for i in range(len(mem_results)):
            mem_text = mem_text + mem_results[i]["entry"]["content"]
            if i < len(mem_results) - 1:
                mem_text = mem_text + "; "
        agent.add_thought(chain, "I recall: " + mem_text)
    else:
        agent.add_thought(chain, "No specific memory found, using general knowledge")
    # Step 2: Classify the question
    let topic = "general"
    if contains(lp, "for") or contains(lp, "loop") or contains(lp, "while") or contains(lp, "iteration"):
        topic = "loops"
    if contains(lp, "import") or contains(lp, "module") or contains(lp, "library"):
        topic = "modules"
    if contains(lp, "class") or contains(lp, "object") or contains(lp, "inherit"):
        topic = "oop"
    if contains(lp, "gc") or contains(lp, "garbage") or contains(lp, "memory"):
        topic = "gc"
    if contains(lp, "compile") or contains(lp, "backend") or contains(lp, "llvm") or contains(lp, "emit"):
        topic = "compiler"
    if contains(lp, "array") or contains(lp, "dict") or contains(lp, "list") or contains(lp, "data struct"):
        topic = "data"
    if contains(lp, "function") or contains(lp, "proc") or contains(lp, "closure"):
        topic = "functions"
    if contains(lp, "error") or contains(lp, "exception") or contains(lp, "try") or contains(lp, "catch"):
        topic = "errors"
    if contains(lp, "test") or contains(lp, "debug") or contains(lp, "fix") or contains(lp, "bug"):
        topic = "testing"
    if contains(lp, "thread") or contains(lp, "async") or contains(lp, "channel") or contains(lp, "concurrent"):
        topic = "concurrency"
    if contains(lp, "plan") or contains(lp, "how to build") or contains(lp, "steps") or contains(lp, "roadmap"):
        topic = "planning"
    agent.add_thought(chain, "Topic classified as: " + topic)
    # Step 3: Generate answer based on topic
    let answer = ""
    if topic == "loops":
        answer = "In Sage, use for loops with range:" + chr(10) + "  for i in range(10):" + chr(10) + "      print i" + chr(10) + chr(10) + "Or iterate arrays:" + chr(10) + "  for item in my_array:" + chr(10) + "      print item" + chr(10) + chr(10) + "While loops: while condition: body"
    if topic == "modules":
        answer = "Sage uses dotted imports for 11 library categories:" + chr(10) + "  import os.fat        # OS/baremetal (15 modules)" + chr(10) + "  import net.url       # Networking (8 modules)" + chr(10) + "  import crypto.hash   # Cryptography (6 modules)" + chr(10) + "  import std.regex     # Standard lib (23 modules)" + chr(10) + "  import ml.tensor     # Machine learning (5 modules)" + chr(10) + "  import llm.agent     # LLM/AI (12 modules)" + chr(10) + chr(10) + "The last path component becomes the binding name."
    if topic == "oop":
        answer = "Sage OOP:" + chr(10) + "  class Animal:" + chr(10) + "      proc init(self, name):" + chr(10) + "          self.name = name" + chr(10) + "      proc speak(self):" + chr(10) + "          print self.name" + chr(10) + chr(10) + "  class Dog(Animal):  # inheritance" + chr(10) + "      proc speak(self):" + chr(10) + "          print self.name + " + chr(34) + " barks" + chr(34)
    if topic == "gc":
        answer = "Sage uses a concurrent tri-color mark-sweep GC:" + chr(10) + "  Phase 1 (STW ~50-200us): Root scan, shade gray, enable write barrier" + chr(10) + "  Phase 2 (concurrent):   Process gray objects from mark stack" + chr(10) + "  Phase 3 (STW ~20-50us): Remark, drain barrier-shaded objects" + chr(10) + "  Phase 4 (concurrent):   Sweep white objects in batches" + chr(10) + chr(10) + "SATB write barrier prevents missed objects during concurrent marking." + chr(10) + "Control: gc_collect(), gc_enable(), gc_disable()"
    if topic == "compiler":
        answer = "Sage has 3 compiler backends:" + chr(10) + "  sage --emit-c file.sage         # C source output" + chr(10) + "  sage --compile file.sage        # Compile via C" + chr(10) + "  sage --emit-llvm file.sage      # LLVM IR output" + chr(10) + "  sage --compile-llvm file.sage   # Native via LLVM" + chr(10) + "  sage --emit-asm file.sage       # Direct assembly (x86-64/aarch64/rv64)" + chr(10) + "  sage --compile-native file.sage # Native binary"
    if topic == "data":
        answer = "Sage data structures:" + chr(10) + "  let arr = [1, 2, 3]     # Array" + chr(10) + "  push(arr, 4)             # Append" + chr(10) + "  print arr[0:2]           # Slicing [1, 2]" + chr(10) + "  let d = {}               # Dict" + chr(10) + "  d[key] = value           # Set" + chr(10) + "  let t = (1, 2, 3)        # Tuple (immutable)"
    if topic == "functions":
        answer = "Sage functions:" + chr(10) + "  proc greet(name):" + chr(10) + "      return name" + chr(10) + chr(10) + "  # Closures:" + chr(10) + "  proc make_counter():" + chr(10) + "      let n = 0" + chr(10) + "      proc inc():" + chr(10) + "          n = n + 1" + chr(10) + "          return n" + chr(10) + "      return inc"
    if topic == "errors":
        answer = "Sage exception handling:" + chr(10) + "  try:" + chr(10) + "      raise error_message" + chr(10) + "  catch e:" + chr(10) + "      print e" + chr(10) + "  finally:" + chr(10) + "      cleanup()"
    if topic == "testing":
        answer = "Run tests: bash tests/run_tests.sh (224 tests)" + chr(10) + "  make test          # Compiler tests" + chr(10) + "  make test-selfhost  # Self-hosted tests" + chr(10) + chr(10) + "Debug tips:" + chr(10) + "  - Add gc_disable() for GC segfaults" + chr(10) + "  - Use chr(10) not escape sequences" + chr(10) + "  - Avoid 5+ elif branches"
    if topic == "concurrency":
        answer = "Sage concurrency:" + chr(10) + "  import thread       # OS threads + mutexes" + chr(10) + "  async proc work():  # Async/await" + chr(10) + "  import std.channel   # Go-style channels" + chr(10) + "  import std.atomic    # Atomic operations" + chr(10) + "  import std.rwlock    # Read-write locks"
    if topic == "planning":
        agent.add_thought(chain, "User wants a plan. Let me break this down.")
        answer = "Here is a development plan:" + chr(10) + "  1. Define the feature/goal" + chr(10) + "  2. Create the module in lib/<category>/" + chr(10) + "  3. Start file with gc_disable() if needed" + chr(10) + "  4. Write the implementation" + chr(10) + "  5. Add test in tests/26_stdlib/" + chr(10) + "  6. Update Makefile install section" + chr(10) + "  7. Update README and docs" + chr(10) + "  8. Run: bash tests/run_tests.sh"
    if len(answer) == 0:
        if len(mem_results) > 0:
            answer = "Based on my knowledge: " + mem_results[0]["entry"]["content"]
        else:
            answer = "I can help with: loops, imports, classes, GC, compiler, data structures, functions, errors, testing, concurrency, and planning. What would you like to know?"
    agent.add_thought(chain, "Answering about " + topic)
    agent.set_conclusion(chain, answer)
    # Store reasoning in episodic memory
    engram.store_episodic(memory, "Answered question about " + topic + ": " + question, 0.6)
    return chain

proc sage_llm(prompt):
    let chain = reason(prompt)
    return chain["conclusion"]

let b = bot.create("", "", sage_llm)
persona.apply_persona(b, persona.sage_developer())

proc on_greet(msg, conv):
    return "Hello. I am SageDev with chain-of-thought reasoning and persistent memory. Ask me anything about Sage."
proc on_bye(msg, conv):
    engram.consolidate(memory)
    return "Goodbye. I have consolidated " + str(len(memory["semantic"])) + " memories. Happy coding."
bot.add_intent(b, "greet", ["hello", "hi", "hey"], on_greet)
bot.add_intent(b, "bye", ["bye", "quit", "exit"], on_bye)

let store = session.create_store()
let sess = session.new_session(store, "SageDev")

print "SageLLM Chatbot v1.0.0 (CoT + Engram + Planning)"
print bot.greet(b)
print "Commands: quit, memory, think <question>, plan <goal>"
print ""

let running = true
while running:
    let msg = input("You> ")
    if msg == "quit" or msg == "exit":
        running = false
        print bot.farewell(b)
    if msg == "memory" and running:
        print engram.summary(memory)
    if running and len(msg) > 6 and msg[0] == "t" and msg[1] == "h" and msg[2] == "i" and msg[3] == "n" and msg[4] == "k" and msg[5] == " ":
        let q = ""
        for i in range(len(msg) - 6):
            q = q + msg[6 + i]
        let chain = reason(q)
        print ""
        print agent.format_chain(chain)
    if running and len(msg) > 5 and msg[0] == "p" and msg[1] == "l" and msg[2] == "a" and msg[3] == "n" and msg[4] == " ":
        let goal = ""
        for i in range(len(msg) - 5):
            goal = goal + msg[5 + i]
        let plan = planner.create_plan(goal)
        planner.add_step(plan, "Analyze requirements", "", "", nil)
        planner.add_step(plan, "Create module file", "", "", [0])
        planner.add_step(plan, "Write implementation", "", "", [1])
        planner.add_step(plan, "Write tests", "", "", [2])
        planner.add_step(plan, "Update documentation", "", "", [3])
        planner.add_step(plan, "Run test suite", "", "", [4])
        print ""
        print planner.format_plan(plan)
        engram.store_episodic(memory, "Created plan for: " + goal, 0.8)
    if running and msg != "quit" and msg != "exit" and msg != "memory":
        let is_think = false
        if len(msg) > 5 and msg[0] == "t" and msg[1] == "h" and msg[2] == "i" and msg[3] == "n" and msg[4] == "k":
            is_think = true
        let is_plan = false
        if len(msg) > 4 and msg[0] == "p" and msg[1] == "l" and msg[2] == "a" and msg[3] == "n":
            is_plan = true
        if not is_think and not is_plan:
            engram.store_working(memory, msg, 0.7)
            let resp = bot.respond(b, msg)
            print ""
            print "SageDev> " + resp
            print ""
            session.add_turn(sess, msg, resp)
